# Generated by Django 5.1.6 on 2026-05-06 01:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=190, unique=True)),
                ('descripcion', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Curso',
                'verbose_name_plural': 'Cursos',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('explicacion', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('titulo', models.CharField(max_length=180)),
                ('objetivo', models.TextField(blank=True)),
                ('descripcion', models.TextField()),
                ('contenido_teorico', models.TextField()),
                ('youtube_url', models.URLField(blank=True)),
                ('imagen_url', models.URLField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos', to='curso_acelerado.curso')),
            ],
            options={
                'verbose_name': 'Modulo',
                'verbose_name_plural': 'Modulos',
                'ordering': ['numero'],
                'unique_together': {('curso', 'numero')},
            },
        ),
        migrations.CreateModel(
            name='ImagenModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=120)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='curso_acelerado/infografias/')),
                ('imagen_url', models.URLField(blank=True)),
                ('descripcion', models.TextField(blank=True)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='curso_acelerado.modulo')),
            ],
            options={
                'verbose_name': 'Imagen de modulo',
                'verbose_name_plural': 'Imagenes de modulo',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OpcionRespuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('es_correcta', models.BooleanField(default=False)),
                ('orden', models.PositiveSmallIntegerField(default=1)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='curso_acelerado.pregunta')),
            ],
            options={
                'verbose_name': 'Opcion de respuesta',
                'verbose_name_plural': 'Opciones de respuesta',
                'ordering': ['orden', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=160)),
                ('porcentaje_aprobacion', models.PositiveSmallIntegerField(default=70)),
                ('activo', models.BooleanField(default=True)),
                ('modulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='curso_acelerado.modulo')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
            },
        ),
        migrations.AddField(
            model_name='pregunta',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='curso_acelerado.quiz'),
        ),
        migrations.CreateModel(
            name='IntentoQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('aprobado', models.BooleanField(default=False)),
                ('correctas', models.PositiveSmallIntegerField(default=0)),
                ('total_preguntas', models.PositiveSmallIntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos_curso', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='intentos', to='curso_acelerado.quiz')),
            ],
            options={
                'verbose_name': 'Intento de quiz',
                'verbose_name_plural': 'Intentos de quiz',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='RespuestaAlumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_correcta', models.BooleanField(default=False)),
                ('intento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='curso_acelerado.intentoquiz')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso_acelerado.opcionrespuesta')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso_acelerado.pregunta')),
            ],
            options={
                'verbose_name': 'Respuesta de alumno',
                'verbose_name_plural': 'Respuestas de alumno',
            },
        ),
        migrations.CreateModel(
            name='ProgresoCurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modulos_completados', models.PositiveSmallIntegerField(default=0)),
                ('porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('iniciado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='curso_acelerado.curso')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_curso', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de curso',
                'verbose_name_plural': 'Progresos de curso',
                'unique_together': {('usuario', 'curso')},
            },
        ),
        migrations.CreateModel(
            name='ProgresoModulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('bloqueado', 'Bloqueado'), ('disponible', 'Disponible'), ('completado', 'Completado')], default='bloqueado', max_length=20)),
                ('mejor_puntaje', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('intentos', models.PositiveIntegerField(default=0)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos', to='curso_acelerado.modulo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progresos_modulo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Progreso de modulo',
                'verbose_name_plural': 'Progresos de modulo',
                'unique_together': {('usuario', 'modulo')},
            },
        ),
    ]
