# Generated by Django 5.1.6 on 2026-08-31 04:04

import django.db.models.deletion
import punto_de_partida.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('equipo', 'Equipo')], max_length=10)),
                ('nombre', models.CharField(max_length=60)),
                ('codigo_equipo', models.CharField(blank=True, default='', max_length=6)),
                ('capital_inicial', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('capital_actual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('deuda', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('colchon_disponible', models.BooleanField(default=False)),
                ('colchon_usado', models.BooleanField(default=False)),
                ('penalizacion_ronda2', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=punto_de_partida.models.generar_token, max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('peso_tier', models.CharField(blank=True, default='', max_length=20)),
                ('peso_valor', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=6)),
                ('monto_asignado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('habilidad', models.CharField(blank=True, default='', max_length=30)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='punto_de_partida.participante')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=6, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('lobby', 'Lobby'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada')], default='lobby', max_length=12)),
                ('ronda_actual', models.PositiveSmallIntegerField(default=0)),
                ('ronda_estado', models.CharField(choices=[('inactiva', 'Inactiva'), ('activa', 'Activa'), ('revelada', 'Revelada')], default='inactiva', max_length=12)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partidas_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
        migrations.AddField(
            model_name='participante',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='punto_de_partida.partida'),
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.PositiveSmallIntegerField()),
                ('opcion', models.CharField(max_length=40)),
                ('extra', models.JSONField(blank=True, default=dict)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='punto_de_partida.miembro')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='punto_de_partida.participante')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
            },
        ),
        migrations.CreateModel(
            name='HistorialCapital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronda', models.PositiveSmallIntegerField()),
                ('capital', models.DecimalField(decimal_places=2, max_digits=14)),
                ('deuda', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('detalle', models.JSONField(blank=True, default=dict)),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='punto_de_partida.participante')),
            ],
            options={
                'verbose_name': 'Historial de capital',
                'verbose_name_plural': 'Historial de capital',
                'ordering': ['participante_id', 'ronda'],
                'constraints': [models.UniqueConstraint(fields=('participante', 'ronda'), name='pdp_historial_unico')],
            },
        ),
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(fields=('partida', 'nombre'), name='pdp_nombre_unico_por_partida'),
        ),
        migrations.AddConstraint(
            model_name='participante',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'equipo')), fields=('partida', 'codigo_equipo'), name='pdp_codigo_equipo_unico_por_partida'),
        ),
        migrations.AddConstraint(
            model_name='voto',
            constraint=models.UniqueConstraint(fields=('miembro', 'ronda'), name='pdp_un_voto_por_miembro_y_ronda'),
        ),
    ]
