# Generated by Django 5.1.6 on 2025-11-18 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarreraRata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gasto_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuentes_ingreso', models.IntegerField()),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('puntaje_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('ERP', 'ERP Empresas'), ('FIN', 'Finanzas Personas')], max_length=3)),
                ('precio_mensual', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mercadopago_preapproval_url', models.URLField()),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
                ('family_status', models.CharField(max_length=100)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debts', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClientePerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('experiencia_emprendimientos', models.PositiveSmallIntegerField(default=0, help_text='Nivel de experiencia en emprendimientos (0 a 10)')),
                ('hijos_a_cargo', models.PositiveIntegerField(default=0)),
                ('plan_activo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tiene_curso', models.BooleanField(default=False)),
                ('acceso_chatbot', models.BooleanField(default=False)),
                ('acceso_quiz', models.BooleanField(default=True)),
                ('diagnosticos_realizados', models.PositiveIntegerField(default=0)),
                ('quiz_score_total', models.IntegerField(default=0)),
                ('quiz_rank', models.IntegerField(blank=True, null=True)),
                ('total_referred', models.PositiveIntegerField(default=0)),
                ('referral_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referral_code', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('ultimo_feedback', models.TextField(blank=True, null=True)),
                ('perfil_asignado', models.CharField(blank=True, max_length=100, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('referido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referidos', to='calculadora.clienteperfil')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('horas_trabajadas', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('ingreso_trabajo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingreso_negocio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingreso_rentas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingreso_inversiones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingreso_otros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_necesarios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_innecesarios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_financieros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_inversiones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('patrimonio_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deuda_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('reaccion_perdida', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil_asignado', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='calculadora.clienteperfil')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_percentage', models.IntegerField()),
                ('property_percentage', models.IntegerField()),
                ('education_percentage', models.IntegerField()),
                ('investment_percentage', models.IntegerField()),
                ('business_percentage', models.IntegerField()),
                ('leisure_percentage', models.IntegerField()),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('perfil_generado', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil_resumen', models.TextField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.player')),
            ],
        ),
        migrations.CreateModel(
            name='QuizParticipacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('puntaje', models.IntegerField(default=0)),
                ('correctas', models.IntegerField(default=0)),
                ('usadas_ayuda', models.BooleanField(default=False)),
                ('duracion', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_quiz', to='calculadora.clienteperfil')),
            ],
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='calculadora.quizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='Subscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preapproval_id', models.CharField(max_length=120, unique=True)),
                ('estado', models.CharField(choices=[('active', 'Activa'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], default='active', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculadora.plan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
