# Generated by Django 5.1 on 2024-09-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarreraRata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gasto_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuentes_ingreso', models.IntegerField()),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('categoria_final', models.CharField(blank=True, max_length=50)),
            ],
        ),
    ]
