# Generated by Django 5.1.6 on 2026-01-30 22:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarreraRata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio_neto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('ingreso_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('gasto_mensual', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuentes_ingreso', models.IntegerField()),
                ('horas_trabajadas', models.DecimalField(decimal_places=2, max_digits=4)),
                ('puntaje_final', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('precio', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
                ('family_status', models.CharField(max_length=100)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debts', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='ClientePerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.PositiveIntegerField(blank=True, null=True)),
                ('experiencia_emprendimientos', models.PositiveSmallIntegerField(default=0, help_text='Nivel de experiencia en emprendimientos (0 a 10)')),
                ('hijos_a_cargo', models.PositiveIntegerField(default=0)),
                ('situacion_habitacional', models.CharField(blank=True, choices=[('propietario', 'Casa propia'), ('alquila', 'Alquila')], max_length=20, null=True)),
                ('objetivos', models.JSONField(blank=True, default=list)),
                ('plan_activo', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tiene_curso', models.BooleanField(default=False)),
                ('acceso_chatbot', models.BooleanField(default=False)),
                ('acceso_quiz', models.BooleanField(default=True)),
                ('diagnosticos_realizados', models.PositiveIntegerField(default=0)),
                ('quiz_score_total', models.IntegerField(default=0)),
                ('quiz_rank', models.IntegerField(blank=True, null=True)),
                ('total_referred', models.PositiveIntegerField(default=0)),
                ('referral_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('referral_code', models.CharField(blank=True, max_length=12, null=True, unique=True)),
                ('ultimo_feedback', models.TextField(blank=True, null=True)),
                ('perfil_asignado', models.CharField(blank=True, max_length=100, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('referido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referidos', to='calculadora.clienteperfil')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DiagnosticoFinanciero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('horas_trabajadas', models.DecimalField(decimal_places=1, default=0, max_digits=4)),
                ('ingreso_trabajo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingreso_negocio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingreso_rentas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingreso_inversiones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingreso_otros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_necesarios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_innecesarios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_financieros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_inversiones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('patrimonio_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deuda_total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('patrimonio_comp', models.JSONField(blank=True, default=dict)),
                ('deuda_comp', models.JSONField(blank=True, default=dict)),
                ('reaccion_perdida', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil_asignado', models.CharField(blank=True, max_length=100, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosticos', to='calculadora.clienteperfil')),
            ],
        ),
        migrations.CreateModel(
            name='MercadoPagoPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=64, unique=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
                ('external_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan_id', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_payment_id', models.CharField(max_length=100, unique=True)),
                ('mp_preference_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], max_length=20)),
                ('amount', models.IntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculadora.plan')),
            ],
        ),
        migrations.CreateModel(
            name='GiftRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_destinatario', models.CharField(max_length=100)),
                ('telefono_destinatario', models.CharField(max_length=20)),
                ('mensaje', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pagado', models.BooleanField(default=False)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.plan')),
            ],
        ),
        migrations.CreateModel(
            name='GiftPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destinatario_nombre', models.CharField(max_length=120)),
                ('destinatario_telefono', models.CharField(max_length=20)),
                ('mp_preference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mp_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regalos_comprados', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculadora.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calculadora.pago')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculadora.plan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_activos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_percentage', models.IntegerField()),
                ('property_percentage', models.IntegerField()),
                ('education_percentage', models.IntegerField()),
                ('investment_percentage', models.IntegerField()),
                ('business_percentage', models.IntegerField()),
                ('leisure_percentage', models.IntegerField()),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('perfil_generado', models.CharField(blank=True, max_length=100, null=True)),
                ('perfil_resumen', models.TextField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.player')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('max_uses', models.PositiveIntegerField(default=1)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.plan')),
            ],
        ),
        migrations.CreateModel(
            name='QuizParticipacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('puntaje', models.IntegerField(default=0)),
                ('correctas', models.IntegerField(default=0)),
                ('usadas_ayuda', models.BooleanField(default=False)),
                ('duracion', models.IntegerField(default=0)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participaciones_quiz', to='calculadora.clienteperfil')),
            ],
        ),
        migrations.CreateModel(
            name='QuizOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('is_correct', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='calculadora.quizquestion')),
            ],
        ),
        migrations.CreateModel(
            name='RegaloPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_destinatario', models.CharField(max_length=20)),
                ('nombre_destinatario', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=120, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activado', models.BooleanField(default=False)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regalos_realizados', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regalos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Subscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preapproval_id', models.CharField(max_length=120, unique=True)),
                ('estado', models.CharField(choices=[('active', 'Activa'), ('paused', 'Pausada'), ('cancelled', 'Cancelada')], default='active', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculadora.plan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_hash', models.CharField(max_length=64)),
                ('modelo_ia', models.CharField(max_length=50)),
                ('bloque_diagnostico', models.TextField(default='')),
                ('bloque_estructura', models.TextField(default='')),
                ('bloque_sesgo', models.TextField(default='')),
                ('bloque_proyeccion', models.TextField(default='')),
                ('bloque_accion', models.TextField(default='')),
                ('bloque_cierre', models.TextField(default='')),
                ('proy_pos', models.JSONField(default=list)),
                ('proy_med', models.JSONField(default=list)),
                ('proy_neg', models.JSONField(default=list)),
                ('creado', models.DateTimeField(default=django.utils.timezone.now)),
                ('esta_bloqueado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('usuario', 'input_hash')},
            },
        ),
    ]
