# Generated by Django 5.1.6 on 2025-10-23 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteperfil',
            name='experiencia_emprendimientos',
            field=models.PositiveSmallIntegerField(default=0, help_text='Nivel de experiencia en emprendimientos (0 a 10)'),
        ),
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='horas_trabajadas',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=4),
        ),
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='reaccion_perdida',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
