# Generated by Django 5.1.6 on 2026-02-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoia',
            name='contenido',
            field=models.TextField(default=''),
        ),
    ]
