# Generated by Django 5.1.6 on 2025-02-25 02:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('Hombre', 'Hombre'), ('Mujer', 'Mujer'), ('Otro', 'Otro')], max_length=10)),
                ('score', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('age', models.IntegerField()),
                ('family_status', models.CharField(max_length=100)),
                ('income', models.DecimalField(decimal_places=2, max_digits=10)),
                ('debts', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('property_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('education_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('investment_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('leisure_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('score', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.player')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.scenario')),
            ],
        ),
    ]
