# Generated by Django 5.1.6 on 2025-11-21 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='activo',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='precio_mensual',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='tipo',
        ),
        migrations.AddField(
            model_name='plan',
            name='precio',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plan',
            name='tipo_pago',
            field=models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('cuatrimestral', 'Cuatrimestral'), ('anual', 'Anual')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='plan',
            name='mercadopago_preapproval_url',
            field=models.URLField(max_length=600),
        ),
        migrations.AlterField(
            model_name='plan',
            name='nombre',
            field=models.CharField(max_length=200),
        ),
    ]
