# Generated by Django 5.1 on 2024-09-19 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrerarata',
            name='categoria_final',
        ),
        migrations.AddField(
            model_name='carrerarata',
            name='puntaje_final',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
