# Generated by Django 5.1.6 on 2026-02-03 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosticofinanciero',
            name='horas_trabajadas',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Horas trabajadas por día', max_digits=4),
        ),
    ]
