# Generated by Django 5.1.6 on 2025-04-17 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0002_player_scenario_playerresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playerresult',
            name='scenario',
        ),
        migrations.AddField(
            model_name='playerresult',
            name='business_percentage',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='playerresult',
            name='perfil_generado',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='playerresult',
            name='perfil_resumen',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerresult',
            name='education_percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerresult',
            name='investment_percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerresult',
            name='leisure_percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerresult',
            name='property_percentage',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='playerresult',
            name='vehicle_percentage',
            field=models.IntegerField(),
        ),
    ]
