# Generated by Django 5.1.6 on 2026-02-11 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0002_resultadoia_contenido'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoia',
            name='error_msg',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='resultadoia',
            name='estado',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='resultadoia',
            name='bloque_diagnostico',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='resultadoia',
            name='contenido',
            field=models.TextField(blank=True, default=''),
        ),
    ]
