# Generated by Django 5.1.6 on 2025-12-17 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0002_remove_plan_activo_remove_plan_precio_mensual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='mercadopago_preapproval_url',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='tipo_pago',
        ),
        migrations.AddField(
            model_name='plan',
            name='preference_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
