# Generated by Django 5.1.6 on 2025-12-19 20:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0003_remove_plan_mercadopago_preapproval_url_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='preference_id',
        ),
        migrations.CreateModel(
            name='GiftPurchase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('destinatario_nombre', models.CharField(max_length=120)),
                ('destinatario_telefono', models.CharField(max_length=20)),
                ('mp_preference_id', models.CharField(blank=True, max_length=255, null=True)),
                ('mp_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(choices=[('pending', 'Pendiente'), ('paid', 'Pagado'), ('cancelled', 'Cancelado')], default='pending', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regalos_comprados', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculadora.plan')),
            ],
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mp_payment_id', models.CharField(max_length=100, unique=True)),
                ('mp_preference_id', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], max_length=20)),
                ('amount', models.IntegerField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('pagador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pagos_realizados', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculadora.plan')),
            ],
        ),
        migrations.CreateModel(
            name='PlanActivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('asignado_en', models.DateTimeField(auto_now_add=True)),
                ('pago', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='calculadora.pago')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='calculadora.plan')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes_activos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RegaloPendiente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_destinatario', models.CharField(max_length=20)),
                ('nombre_destinatario', models.CharField(max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=120, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('activado', models.BooleanField(default=False)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regalos_realizados', to=settings.AUTH_USER_MODEL)),
                ('destinatario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='regalos_recibidos', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.plan')),
            ],
        ),
    ]
