# Generated by Django 5.1.6 on 2026-02-12 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0003_resultadoia_error_msg_resultadoia_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoia',
            name='tokens_usados',
            field=models.IntegerField(default=0),
        ),
    ]
