# Generated by Django 5.1.6 on 2026-03-03 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0004_resultadoia_tokens_usados'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultadoia',
            name='costo_estimado_usd',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=10),
        ),
    ]
