# Generated by Django 5.1.6 on 2026-03-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0005_resultadoia_costo_estimado_usd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteperfil',
            name='plan_activo',
            field=models.PositiveSmallIntegerField(blank=True, default=1, null=True),
        ),
    ]
