# Generated by Django 5.1.6 on 2026-03-18 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0006_alter_clienteperfil_plan_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteperfil',
            name='alias',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
