# Generated by Django 5.1.6 on 2025-07-06 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0006_guestcounter_remove_userscore_name_userscore_alias_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='games_played',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='incorrect_answers',
            field=models.IntegerField(default=0),
        ),
    ]
