# Generated by Django 5.1.6 on 2025-07-09 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0007_userprofile_correct_answers_userprofile_games_played_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='alias_confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
