# Generated by Django 5.1.6 on 2026-01-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0007_giftrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='clienteperfil',
            name='situacion_habitacional',
            field=models.CharField(blank=True, choices=[('casa_propia', 'Casa propia'), ('alquila', 'Alquila')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='deuda_comp',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='patrimonio_comp',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
