# Generated by Django 5.1.6 on 2026-03-19 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0007_clienteperfil_alias'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'Usuario'), ('assistant', 'Oráculo')], max_length=10)),
                ('content', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_mensajes', to='calculadora.clienteperfil')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
    ]
