# Generated by Django 5.1.6 on 2025-09-30 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0008_userprofile_alias_confirmado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientePerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edad', models.IntegerField()),
                ('estado_civil', models.CharField(max_length=50)),
                ('hijos_a_cargo', models.IntegerField(default=0)),
                ('ingreso_trabajo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingreso_negocio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingreso_rentas', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingreso_inversiones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('ingreso_otros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_necesarios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_innecesarios', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_financieros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_inversiones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('gasto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('patrimonio_vivienda', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('patrimonio_vehiculos', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('patrimonio_ahorros_local', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('patrimonio_ahorros_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('patrimonio_inversiones', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('patrimonio_negocio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('patrimonio_otros', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('deudas', models.TextField(blank=True, null=True)),
                ('objetivos', models.JSONField()),
                ('plazo_inversion', models.CharField(max_length=20)),
                ('reaccion_perdida', models.CharField(max_length=50)),
                ('importancia_dinero', models.JSONField()),
                ('uso_millon', models.JSONField()),
                ('conocimiento_acciones', models.CharField(max_length=100)),
                ('conocimiento_seguridad', models.JSONField()),
                ('liquidez', models.CharField(max_length=20)),
                ('perfil_asignado', models.CharField(blank=True, max_length=50, null=True)),
                ('feedback', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
