# Generated by Django 5.1.6 on 2026-01-26 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0008_clienteperfil_situacion_habitacional_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienteperfil',
            name='situacion_habitacional',
            field=models.CharField(blank=True, choices=[('propietario', 'Casa propia'), ('alquila', 'Alquila')], max_length=20, null=True),
        ),
    ]
