# Generated by Django 5.1.6 on 2026-03-20 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0008_chatmensaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolicitudAsesoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('horario_preferido', models.CharField(blank=True, max_length=100)),
                ('atendida', models.BooleanField(default=False)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_asesoria', to='calculadora.clienteperfil')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
