# Generated by Django 5.1.6 on 2026-01-27 15:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0009_alter_clienteperfil_situacion_habitacional'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_hash', models.CharField(db_index=True, max_length=64)),
                ('contenido', models.TextField()),
                ('modelo_ia', models.CharField(default='gpt-4o-mini', max_length=50)),
                ('tokens_usados', models.IntegerField(default=0)),
                ('costo_estimado_usd', models.DecimalField(decimal_places=6, default=0, max_digits=8)),
                ('esta_bloqueado', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resultados_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
                'unique_together': {('usuario', 'input_hash')},
            },
        ),
    ]
