# Generated by Django 5.1.6 on 2025-10-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0009_clienteperfil'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteperfil',
            name='deudas',
        ),
        migrations.AddField(
            model_name='clienteperfil',
            name='deuda_auto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='clienteperfil',
            name='deuda_casa',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='clienteperfil',
            name='deuda_financiera',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='clienteperfil',
            name='deuda_tarjeta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
