# Generated by Django 5.1.6 on 2025-10-03 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0010_remove_clienteperfil_deudas_clienteperfil_deuda_auto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienteperfil',
            name='gasto_total',
        ),
    ]
