# Generated by Django 5.1.6 on 2026-04-09 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0013_inscripcioncursofintech'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='categoria',
            field=models.CharField(choices=[('acciones', '📈 Acciones'), ('matematica_financiera', '🧮 Matemática Financiera'), ('fci_etf', '📊 FCI o ETF'), ('internacional', '🌍 Internacional'), ('argentina', '🇦🇷 Argentina'), ('fintech', '💡 Fintech')], db_index=True, default='acciones', max_length=30),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='text',
            field=models.CharField(max_length=500),
        ),
    ]
