# Generated by Django 5.1.6 on 2026-04-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0014_quizquestion_categoria_alter_quizquestion_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='causas_estancamiento',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='confianza_sistema',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='conocimiento_financiero',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='estabilidad_laboral',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='estado_financiero',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='importancia_dinero',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='ingreso_emprendimiento',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='limitantes_crecimiento',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='objetivos_ordenados',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='percepcion_estabilidad',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='resolucion_deficit',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='respuestas_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='resultados_emprendimientos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='sesgos_sistema',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
