# Generated by Django 5.1.6 on 2026-04-28 22:55

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0015_diagnosticofinanciero_causas_estancamiento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('sector', models.CharField(choices=[('TECH', 'Tecnologia'), ('AGRO', 'Agro'), ('RETAIL', 'Retail / Consumo'), ('SERVICIOS', 'Servicios'), ('INDUSTRIA', 'Industria')], max_length=20)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('quote_reason', models.CharField(blank=True, choices=[('inversores', 'Busco inversores'), ('curiosidad', 'Solo curiosidad'), ('venta', 'Quiero vender mi empresa'), ('competencia', 'Comparacion con competencia')], default='', max_length=20)),
                ('competitive_advantage', models.CharField(blank=True, default='', max_length=120)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=16)),
                ('employees', models.PositiveIntegerField(default=1)),
                ('years_active', models.PositiveIntegerField(default=0)),
                ('growth_rate', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('ebitda_margin', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6)),
                ('debt_level', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('valuation_initial', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('previous_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('current_price', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16)),
                ('last_noise_percent', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Empresa cotizante',
                'verbose_name_plural': 'Empresas cotizantes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cash_balance', models.DecimalField(decimal_places=2, default=Decimal('5000000.00'), max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='market_portfolio', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BUY', 'Compra'), ('SELL', 'Venta')], max_length=4)),
                ('quantity', models.PositiveIntegerField()),
                ('price_at_transaction', models.DecimalField(decimal_places=2, max_digits=16)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='calculadora.company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
