# Generated by Django 5.1.6 on 2026-04-29 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0016_company_portfolio_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ticker',
            field=models.CharField(blank=True, default='', max_length=8),
        ),
        migrations.AddField(
            model_name='company',
            name='traded_volume',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
