# Generated by Django 5.1.6 on 2026-04-30 14:06

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0017_company_ticker_company_traded_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='gross_margin',
            field=models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=6),
        ),
        migrations.AddField(
            model_name='company',
            name='total_assets',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AlterField(
            model_name='company',
            name='quote_reason',
            field=models.CharField(blank=True, choices=[('inversores', 'Busco inversores'), ('curiosidad', 'Solo curiosidad'), ('venta', 'Quiero vender mi empresa'), ('competencia', 'Comparacion con competencia'), ('expansion', 'Quiero abrir nuevas unidades'), ('socios', 'Busco socios estrategicos'), ('ordenar', 'Quiero ordenar mis numeros'), ('marca', 'Quiero medir mi marca'), ('sucesion', 'Estoy pensando sucesion')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(choices=[('TECH', 'Tecnologia'), ('AGRO', 'Agro'), ('RETAIL', 'Retail / Consumo'), ('SERVICIOS', 'Servicios'), ('INDUSTRIA', 'Industria'), ('GASTRONOMIA', 'Gastronomia'), ('FINANZAS', 'Finanzas'), ('ENTRETENIMIENTO', 'Entretenimiento'), ('INMOBILIARIO', 'Inmobiliario')], max_length=20),
        ),
    ]
