# Generated by Django 5.1.6 on 2026-04-30 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0019_company_legal_structure_alter_company_quote_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='quote_reason',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
