# Generated by Django 5.1.6 on 2026-05-04 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0020_alter_company_quote_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='codigo_anonimo',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='diagnosticofinanciero',
            name='payload_codificado',
            field=models.TextField(blank=True, null=True),
        ),
    ]
