# Generated by Django 5.1.6 on 2026-05-11 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0021_diagnosticofinanciero_codigo_anonimo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listed_companies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='company',
            name='guest_session_key',
            field=models.CharField(blank=True, default='', max_length=80),
        ),
        migrations.CreateModel(
            name='CompanyIpoUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_type', models.CharField(choices=[('info', 'Informacion relevante'), ('problema', 'Problema detectado'), ('solucion', 'Nueva solucion'), ('hito', 'Hito comercial'), ('finanzas', 'Dato financiero')], max_length=20)),
                ('impact', models.CharField(choices=[('positivo', 'Impacto positivo'), ('neutral', 'Impacto neutral'), ('negativo', 'Impacto negativo')], default='neutral', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipo_updates', to='calculadora.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
