# Generated by Django 5.1.6 on 2026-05-13 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0024_companyipocomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active_customers',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
