# Generated by Django 5.1.6 on 2026-06-04 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0030_world_intelligence_pro'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalOffering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Borrador'), ('open', 'Reservas abiertas'), ('closed', 'Cerrada')], default='draft', max_length=16)),
                ('summary', models.TextField()),
                ('location', models.CharField(max_length=120)),
                ('founder_name', models.CharField(max_length=120)),
                ('public_contact', models.CharField(max_length=160)),
                ('capital_target', models.DecimalField(decimal_places=2, max_digits=16)),
                ('minimum_reservation', models.DecimalField(decimal_places=2, max_digits=16)),
                ('offered_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expansion_plan', models.TextField()),
                ('use_of_funds', models.TextField()),
                ('milestone_1', models.CharField(max_length=240)),
                ('milestone_2', models.CharField(max_length=240)),
                ('milestone_3', models.CharField(max_length=240)),
                ('reporting_frequency', models.CharField(max_length=120)),
                ('information_commitment', models.TextField()),
                ('shareholder_decisions', models.TextField()),
                ('capital_release_terms', models.TextField()),
                ('risks', models.TextField()),
                ('contract_terms', models.TextField()),
                ('contract_version', models.PositiveIntegerField(default=1)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='capital_offering', to='calculadora.company')),
            ],
            options={
                'verbose_name': 'Apertura de capital',
                'verbose_name_plural': 'Aperturas de capital',
                'ordering': ['-published_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CapitalReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('cancelled', 'Cancelada')], default='active', max_length=16)),
                ('accepted_contract_version', models.PositiveIntegerField()),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='calculadora.capitaloffering')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capital_reservations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reserva de participacion',
                'verbose_name_plural': 'Reservas de participacion',
                'ordering': ['-accepted_at'],
                'constraints': [models.UniqueConstraint(fields=('offering', 'user'), name='unique_user_capital_reservation')],
            },
        ),
    ]
