# Generated by Django 5.1.6 on 2026-06-04 23:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0031_capitaloffering_capitalreservation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=140)),
                ('document_id', models.CharField(max_length=32)),
                ('tax_id', models.CharField(blank=True, default='', max_length=32)),
                ('phone', models.CharField(max_length=40)),
                ('city', models.CharField(max_length=120)),
                ('risk_acknowledged', models.BooleanField(default=False)),
                ('data_consent', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil inversor',
                'verbose_name_plural': 'Perfiles inversores',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='OfferingEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_type', models.CharField(choices=[('financial', 'Finanzas'), ('stock', 'Stock'), ('legal', 'Legal'), ('asset', 'Activo'), ('contract', 'Contrato'), ('photo', 'Foto'), ('other', 'Otro')], default='other', max_length=20)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('declared', 'Declarado'), ('pending', 'Pendiente de verificar'), ('verified', 'Verificado'), ('rejected', 'Rechazado')], default='pending', max_length=16)),
                ('file', models.FileField(blank=True, upload_to='capital_offerings/evidence/')),
                ('external_url', models.URLField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='calculadora.capitaloffering')),
            ],
            options={
                'verbose_name': 'Evidencia de apertura',
                'verbose_name_plural': 'Evidencias de apertura',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfferingQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField(blank=True, default='')),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_offering_questions', to=settings.AUTH_USER_MODEL)),
                ('offering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='calculadora.capitaloffering')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offering_questions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pregunta de apertura',
                'verbose_name_plural': 'Preguntas de apertura',
                'ordering': ['-created_at'],
            },
        ),
    ]
