# Generated by Django 5.1.6 on 2026-06-14 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0033_clienteperfil_referral_commission_paid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='capitalreservation',
            options={'ordering': ['-accepted_at'], 'verbose_name': 'Solicitud de compra de acciones', 'verbose_name_plural': 'Solicitudes de compra de acciones'},
        ),
        migrations.AddField(
            model_name='capitaloffering',
            name='documentation_status',
            field=models.CharField(choices=[('self_declared', 'Autodeclarado'), ('in_conversation', 'En conversacion'), ('pending', 'Documentacion pendiente'), ('documented', 'Documentado'), ('platform_validated', 'Validado por Cordoba Street'), ('third_party_validated', 'Validado por tercero')], default='self_declared', max_length=32),
        ),
        migrations.AddField(
            model_name='capitaloffering',
            name='instrument_stage',
            field=models.CharField(choices=[('private_contact', 'Contacto privado entre partes'), ('legal_agreement', 'Acuerdo legal'), ('smart_contract', 'Smart contract'), ('tokenization', 'Tokenizacion'), ('milestone_funds', 'Fondos por hitos')], default='private_contact', max_length=32),
        ),
        migrations.AlterField(
            model_name='capitaloffering',
            name='status',
            field=models.CharField(choices=[('draft', 'Borrador'), ('open', 'Solicitudes abiertas'), ('closed', 'Cerrada')], default='draft', max_length=16),
        ),
    ]
