# Generated by Django 5.1.6 on 2026-07-11 02:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0034_alter_capitalreservation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='market_visibility',
            field=models.CharField(choices=[('private', 'Privada'), ('public_named', 'Publica con nombre'), ('open_investors', 'Publica abierta a inversores')], default='private', max_length=24),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='cash_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000000.00'), max_digits=16),
        ),
    ]
