# Generated by Django 5.1.6 on 2026-07-14 22:09

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0036_default_opening_capital_to_10m'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='active_customers_next_24m',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='employees_next_24m',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='market_scope_current',
            field=models.CharField(blank=True, choices=[('barrial', 'Barrial'), ('zona_norte', 'Zona norte'), ('zona_sur', 'Zona sur'), ('cordoba_capital', 'Cordoba capital'), ('interior', 'Interior provincial'), ('provincia', 'Toda Cordoba'), ('regional', 'Region centro'), ('nacional', 'Nacional'), ('exportable', 'Exportable')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='market_scope_future',
            field=models.CharField(blank=True, choices=[('barrial', 'Barrial'), ('zona_norte', 'Zona norte'), ('zona_sur', 'Zona sur'), ('cordoba_capital', 'Cordoba capital'), ('interior', 'Interior provincial'), ('provincia', 'Toda Cordoba'), ('regional', 'Region centro'), ('nacional', 'Nacional'), ('exportable', 'Exportable')], default='', max_length=32),
        ),
        migrations.AddField(
            model_name='company',
            name='perceived_valuation',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='company',
            name='perceived_valuation_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='company',
            name='revenue_next_24m',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.CreateModel(
            name='CompanyValuationReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perceived_value', models.DecimalField(decimal_places=2, max_digits=16)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('in_review', 'En analisis'), ('answered', 'Respondida'), ('service_offered', 'Servicio ofrecido'), ('closed', 'Cerrada')], default='pending', max_length=20)),
                ('internal_notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_reviews', to='calculadora.company')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de revision de valuacion',
                'verbose_name_plural': 'Solicitudes de revision de valuacion',
                'ordering': ['-created_at'],
            },
        ),
    ]
