# Generated by Django 5.1.6 on 2026-07-25 04:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0037_company_active_customers_next_24m_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NaifCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('item', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('supplier', models.CharField(blank=True, default='', max_length=120)),
                ('paid', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NAIF costo',
                'verbose_name_plural': 'NAIF costos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NaifSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('client', models.CharField(max_length=120)),
                ('product_code', models.CharField(blank=True, default='', max_length=24)),
                ('product_name', models.CharField(blank=True, default='', max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NAIF venta',
                'verbose_name_plural': 'NAIF ventas',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
