# Generated by Django 5.1.6 on 2026-07-25 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0038_naifcost_naifsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='naifcost',
            name='import_key',
            field=models.CharField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='naifcost',
            name='source_file',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='naifsale',
            name='import_key',
            field=models.CharField(blank=True, max_length=180, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='naifsale',
            name='source_file',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
    ]
