# Generated by Django 5.1.6 on 2026-07-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0039_naifcost_import_key_naifcost_source_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaifPremiumAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='NAIF', max_length=80)),
                ('enable_ytd', models.BooleanField(default=False)),
                ('enable_last_30_days', models.BooleanField(default=False)),
                ('enable_last_week', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NAIF acceso premium',
                'verbose_name_plural': 'NAIF accesos premium',
            },
        ),
    ]
