# Generated by Django 5.1.6 on 2026-07-26 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0040_naifpremiumaccess'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NaifPremiumAccess',
        ),
    ]
