# Generated by Django 5.1.6 on 2026-07-27 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0041_delete_naifpremiumaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='NaifClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NAIF cliente',
                'verbose_name_plural': 'NAIF clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NaifProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('suggested_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NAIF producto',
                'verbose_name_plural': 'NAIF productos',
                'ordering': ['name'],
            },
        ),
    ]
