# Generated by Django 5.1.6 on 2026-07-29 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0043_naifcostcategory_naifclient_current_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='naifcostcategory',
            name='show_in_metrics',
            field=models.BooleanField(default=True),
        ),
    ]
