# Generated by Django 5.1.6 on 2026-07-30 03:56

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0044_naifcostcategory_show_in_metrics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueDollarRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('buy', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sell', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('source', models.CharField(blank=True, default='Bluelytics', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dolar blue historico',
                'verbose_name_plural': 'Dolar blue historico',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='PersonalExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'NAIF categoria gasto personal',
                'verbose_name_plural': 'NAIF categorias gasto personal',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PersonalWalletSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_currency', models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'USD blue')], default='ARS', max_length=3)),
                ('investment_suggestion_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'NAIF billetera configuracion',
                'verbose_name_plural': 'NAIF billetera configuracion',
            },
        ),
        migrations.CreateModel(
            name='PersonalWalletMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('kind', models.CharField(choices=[('expense', 'Gasto'), ('income', 'Ingreso')], default='expense', max_length=12)),
                ('description', models.CharField(blank=True, default='', max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_method', models.CharField(blank=True, default='', max_length=80)),
                ('notes', models.CharField(blank=True, default='', max_length=240)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('naif_profit', 'Ganancia NAIF')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculadora.personalexpensecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'NAIF movimiento billetera',
                'verbose_name_plural': 'NAIF movimientos billetera',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PersonalBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.personalexpensecategory')),
            ],
            options={
                'verbose_name': 'NAIF presupuesto personal',
                'verbose_name_plural': 'NAIF presupuestos personales',
                'ordering': ['-year', '-month', 'category__name'],
                'unique_together': {('category', 'year', 'month')},
            },
        ),
    ]
