# Generated by Django 5.1.6 on 2026-08-19 11:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0045_bluedollarrate_personalexpensecategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RodriguezClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('current_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rodriguez cliente',
                'verbose_name_plural': 'Rodriguez clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RodriguezCostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('show_in_metrics', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rodriguez rubro de costo',
                'verbose_name_plural': 'Rodriguez rubros de costo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RodriguezProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('suggested_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Rodriguez producto',
                'verbose_name_plural': 'Rodriguez productos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RodriguezCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('item', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('supplier', models.CharField(blank=True, default='', max_length=120)),
                ('paid', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rodriguez costo',
                'verbose_name_plural': 'Rodriguez costos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RodriguezSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('client', models.CharField(max_length=120)),
                ('product_code', models.CharField(blank=True, default='', max_length=24)),
                ('product_name', models.CharField(blank=True, default='', max_length=120)),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('paid', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rodriguez venta',
                'verbose_name_plural': 'Rodriguez ventas',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RodriguezCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calculadora.rodriguezcostcategory')),
            ],
            options={
                'verbose_name': 'Rodriguez item de costo',
                'verbose_name_plural': 'Rodriguez items de costo',
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
    ]
