# Generated by Django 5.1.6 on 2026-08-23 12:08

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0046_rodriguezclient_rodriguezcostcategory_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DibuClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('address', models.CharField(blank=True, default='', max_length=180)),
                ('notes', models.CharField(blank=True, default='', max_length=240)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dibu cliente',
                'verbose_name_plural': 'Dibu clientes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DibuCostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('show_in_metrics', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dibu rubro de costo',
                'verbose_name_plural': 'Dibu rubros de costo',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DibuExpenseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('color', models.CharField(blank=True, default='', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dibu categoria gasto personal',
                'verbose_name_plural': 'Dibu categorias gasto personal',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DibuHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('default_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dibu ayudante',
                'verbose_name_plural': 'Dibu ayudantes',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DibuServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dibu tipo de servicio',
                'verbose_name_plural': 'Dibu tipos de servicio',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DibuVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=24, unique=True)),
                ('name', models.CharField(max_length=80)),
                ('plate', models.CharField(blank=True, default='', max_length=16)),
                ('kind', models.CharField(choices=[('truck', 'Camion / Chasis'), ('pickup', 'Pickup')], default='truck', max_length=12)),
                ('image', models.CharField(blank=True, default='', help_text='Nombre del archivo en static/calculadora/img/', max_length=120)),
                ('capacity_kg', models.PositiveIntegerField(default=0)),
                ('odometer_km', models.DecimalField(decimal_places=1, default=0, max_digits=12)),
                ('active', models.BooleanField(default=True)),
                ('tires_last_km', models.DecimalField(decimal_places=1, default=0, max_digits=12)),
                ('tires_interval_km', models.PositiveIntegerField(default=40000)),
                ('belt_last_km', models.DecimalField(decimal_places=1, default=0, max_digits=12)),
                ('belt_interval_km', models.PositiveIntegerField(default=60000)),
                ('notes', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dibu vehiculo',
                'verbose_name_plural': 'Dibu vehiculos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DibuWalletSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_currency', models.CharField(choices=[('ARS', 'Pesos'), ('USD', 'USD blue')], default='ARS', max_length=3)),
                ('investment_suggestion_percent', models.DecimalField(decimal_places=2, default=Decimal('5.00'), max_digits=5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Dibu billetera configuracion',
                'verbose_name_plural': 'Dibu billetera configuracion',
            },
        ),
        migrations.CreateModel(
            name='DibuQuote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('client', models.CharField(max_length=120)),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('service_name', models.CharField(blank=True, default='', max_length=120)),
                ('origin', models.CharField(blank=True, default='', max_length=180)),
                ('destination', models.CharField(blank=True, default='', max_length=180)),
                ('km', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('notes', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dibu presupuesto',
                'verbose_name_plural': 'Dibu presupuestos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DibuTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('client', models.CharField(max_length=120)),
                ('client_phone', models.CharField(blank=True, default='', max_length=40)),
                ('service_code', models.CharField(blank=True, default='', max_length=32)),
                ('service_name', models.CharField(blank=True, default='', max_length=120)),
                ('origin', models.CharField(blank=True, default='', max_length=180)),
                ('destination', models.CharField(blank=True, default='', max_length=180)),
                ('km', models.DecimalField(decimal_places=1, default=0, max_digits=10)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('extra', models.DecimalField(decimal_places=2, default=0, help_text='Peajes, escalera, piso alto, etc.', max_digits=12)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('helpers_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('paid', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='calculadora.dibuvehicle')),
            ],
            options={
                'verbose_name': 'Dibu viaje',
                'verbose_name_plural': 'Dibu viajes',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DibuTripHelper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('helper_name', models.CharField(max_length=120)),
                ('fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='helper_rows', to='calculadora.dibutrip')),
            ],
            options={
                'verbose_name': 'Dibu ayudante en viaje',
                'verbose_name_plural': 'Dibu ayudantes en viajes',
                'ordering': ['helper_name'],
            },
        ),
        migrations.CreateModel(
            name='DibuFuelLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('liters', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('odometer_km', models.DecimalField(decimal_places=1, default=0, max_digits=12)),
                ('station', models.CharField(blank=True, default='', max_length=120)),
                ('full_tank', models.BooleanField(default=True, help_text='Tanque lleno: permite calcular consumo real')),
                ('notes', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_loads', to='calculadora.dibuvehicle')),
            ],
            options={
                'verbose_name': 'Dibu carga de combustible',
                'verbose_name_plural': 'Dibu cargas de combustible',
                'ordering': ['-date', '-odometer_km', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DibuCost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('category', models.CharField(blank=True, default='', max_length=80)),
                ('item', models.CharField(max_length=120)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('supplier', models.CharField(blank=True, default='', max_length=120)),
                ('paid', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=240)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='costs', to='calculadora.dibuvehicle')),
            ],
            options={
                'verbose_name': 'Dibu costo',
                'verbose_name_plural': 'Dibu costos',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DibuWalletMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('kind', models.CharField(choices=[('expense', 'Gasto'), ('income', 'Ingreso')], default='expense', max_length=12)),
                ('description', models.CharField(blank=True, default='', max_length=180)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('payment_method', models.CharField(blank=True, default='', max_length=80)),
                ('notes', models.CharField(blank=True, default='', max_length=240)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('dibu_profit', 'Ganancia El Flete de Dibu')], default='manual', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calculadora.dibuexpensecategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dibu movimiento billetera',
                'verbose_name_plural': 'Dibu movimientos billetera',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DibuCostItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='calculadora.dibucostcategory')),
            ],
            options={
                'verbose_name': 'Dibu item de costo',
                'verbose_name_plural': 'Dibu items de costo',
                'ordering': ['category__name', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='DibuBudget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('month', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calculadora.dibuexpensecategory')),
            ],
            options={
                'verbose_name': 'Dibu presupuesto personal',
                'verbose_name_plural': 'Dibu presupuestos personales',
                'ordering': ['-year', '-month', 'category__name'],
                'unique_together': {('category', 'year', 'month')},
            },
        ),
    ]
