# Generated by Django 5.1.6 on 2026-09-12 02:16

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0047_dibuclient_dibucostcategory_dibuexpensecategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='valuation_high',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
        migrations.AddField(
            model_name='company',
            name='valuation_low',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16),
        ),
    ]
