# Generated by Django 5.1.6 on 2026-09-12 03:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0048_company_valuation_high_company_valuation_low'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationInvite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('contact_name', models.CharField(max_length=120)),
                ('contact_note', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='valuation_invite', to='calculadora.company')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='valuation_invites_sent', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Invitacion a cotizar',
                'verbose_name_plural': 'Invitaciones a cotizar',
                'ordering': ['-created_at'],
            },
        ),
    ]
