# Generated by Django 5.1.6 on 2026-09-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calculadora', '0049_valuationinvite'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='sector_secondary',
            field=models.CharField(blank=True, choices=[('TECH', 'Tecnologia'), ('AGRO', 'Agro'), ('RETAIL', 'Retail / Consumo'), ('SERVICIOS', 'Servicios profesionales'), ('INDUSTRIA', 'Industria'), ('GASTRONOMIA', 'Gastronomia'), ('FINANZAS', 'Finanzas'), ('ENTRETENIMIENTO', 'Entretenimiento'), ('INMOBILIARIO', 'Inmobiliario'), ('LOGISTICA', 'Logistica'), ('EDUCACION', 'Educacion'), ('CONSTRUCCION', 'Construccion'), ('TRANSPORTE', 'Transporte y movilidad'), ('SALUD', 'Salud y bienestar')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='sector',
            field=models.CharField(choices=[('TECH', 'Tecnologia'), ('AGRO', 'Agro'), ('RETAIL', 'Retail / Consumo'), ('SERVICIOS', 'Servicios profesionales'), ('INDUSTRIA', 'Industria'), ('GASTRONOMIA', 'Gastronomia'), ('FINANZAS', 'Finanzas'), ('ENTRETENIMIENTO', 'Entretenimiento'), ('INMOBILIARIO', 'Inmobiliario'), ('LOGISTICA', 'Logistica'), ('EDUCACION', 'Educacion'), ('CONSTRUCCION', 'Construccion'), ('TRANSPORTE', 'Transporte y movilidad'), ('SALUD', 'Salud y bienestar')], max_length=20),
        ),
    ]
