# Generated by Django 5.1.6 on 2026-09-03 03:03

import charla_votacion.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveIntegerField()),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=240)),
                ('cerrada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(default=charla_votacion.models.generar_codigo, max_length=8, unique=True)),
                ('nombre', models.CharField(default='Charla', max_length=120)),
                ('activa', models.BooleanField(default=True)),
                ('creada', models.DateTimeField(auto_now_add=True)),
                ('prompt_final', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Opcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=120)),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opciones', to='charla_votacion.etapa')),
            ],
        ),
        migrations.AddField(
            model_name='etapa',
            name='ganadora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='charla_votacion.opcion'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='sesion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='charla_votacion.sesion'),
        ),
        migrations.AlterUniqueTogether(
            name='etapa',
            unique_together={('sesion', 'orden')},
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo_id', models.CharField(max_length=64)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos_etapa', to='charla_votacion.etapa')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='charla_votacion.opcion')),
            ],
            options={
                'unique_together': {('etapa', 'dispositivo_id')},
            },
        ),
    ]
