# Generated by Django 5.1.6 on 2026-09-03 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charla_votacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sesion',
            name='posicion_actual',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
