# Generated by Django 5.1.6 on 2026-09-04 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charla_votacion', '0002_sesion_posicion_actual'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interesado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('contacto', models.CharField(max_length=200)),
                ('comentario', models.CharField(blank=True, max_length=300)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interesados', to='charla_votacion.sesion')),
            ],
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dispositivo_id', models.CharField(max_length=64)),
                ('primera_vez', models.DateTimeField(auto_now_add=True)),
                ('ultima_vez', models.DateTimeField(auto_now=True)),
                ('sesion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='charla_votacion.sesion')),
            ],
            options={
                'unique_together': {('sesion', 'dispositivo_id')},
            },
        ),
    ]
