# Generated by Django 5.1.6 on 2026-09-04 01:27

import django.db.models.deletion
import trivia_financiero.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('individual', 'Individual'), ('equipo', 'Equipo')], max_length=10)),
                ('nombre', models.CharField(max_length=60)),
                ('codigo_equipo', models.CharField(blank=True, default='', max_length=6)),
                ('puntaje_total', models.IntegerField(default=0)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Jugador',
                'verbose_name_plural': 'Jugadores',
            },
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=280)),
                ('opciones', models.JSONField()),
                ('respuesta_correcta', models.PositiveSmallIntegerField()),
                ('explicacion', models.TextField(blank=True)),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('media', 'Media'), ('dificil', 'Difícil')], max_length=10)),
                ('categoria', models.CharField(choices=[('ahorro', 'Ahorro'), ('deuda_interes', 'Deuda e interés'), ('inversion_riesgo', 'Inversión y riesgo'), ('presupuesto', 'Presupuesto'), ('otros', 'Otros')], default='otros', max_length=20)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Pregunta',
                'verbose_name_plural': 'Preguntas',
            },
        ),
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, default=trivia_financiero.models.generar_token, max_length=32, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='trivia_financiero.jugador')),
            ],
            options={
                'verbose_name': 'Miembro',
                'verbose_name_plural': 'Miembros',
            },
        ),
        migrations.CreateModel(
            name='Partida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(db_index=True, max_length=6, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=120)),
                ('colegio', models.CharField(blank=True, max_length=120)),
                ('curso', models.CharField(blank=True, max_length=60)),
                ('estado', models.CharField(choices=[('lobby', 'Lobby'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada')], default='lobby', max_length=12)),
                ('pregunta_actual_index', models.PositiveSmallIntegerField(default=0)),
                ('pregunta_estado', models.CharField(choices=[('inactiva', 'Inactiva'), ('activa', 'Activa'), ('revelada', 'Revelada')], default='inactiva', max_length=12)),
                ('pregunta_iniciada_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('host_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trivias_creadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Partida',
                'verbose_name_plural': 'Partidas',
            },
        ),
        migrations.AddField(
            model_name='jugador',
            name='partida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='trivia_financiero.partida'),
        ),
        migrations.CreateModel(
            name='PartidaPregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField()),
                ('partida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='trivia_financiero.partida')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='trivia_financiero.pregunta')),
            ],
            options={
                'verbose_name': 'Pregunta de partida',
                'verbose_name_plural': 'Preguntas de partida',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_elegida', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('es_correcta', models.BooleanField(default=False)),
                ('puntos_obtenidos', models.IntegerField(default=0)),
                ('tiempo_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='trivia_financiero.jugador')),
                ('partida_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='trivia_financiero.partidapregunta')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
        migrations.CreateModel(
            name='VotoMiembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion_elegida', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('tiempo_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('miembro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='trivia_financiero.miembro')),
                ('partida_pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votos', to='trivia_financiero.partidapregunta')),
            ],
            options={
                'verbose_name': 'Voto',
                'verbose_name_plural': 'Votos',
            },
        ),
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.UniqueConstraint(fields=('partida', 'nombre'), name='tf_nombre_unico_por_partida'),
        ),
        migrations.AddConstraint(
            model_name='jugador',
            constraint=models.UniqueConstraint(condition=models.Q(('tipo', 'equipo')), fields=('partida', 'codigo_equipo'), name='tf_codigo_equipo_unico_por_partida'),
        ),
        migrations.AddConstraint(
            model_name='partidapregunta',
            constraint=models.UniqueConstraint(fields=('partida', 'orden'), name='tf_orden_unico_por_partida'),
        ),
        migrations.AddConstraint(
            model_name='respuesta',
            constraint=models.UniqueConstraint(fields=('jugador', 'partida_pregunta'), name='tf_respuesta_unica_por_jugador_y_pregunta'),
        ),
        migrations.AddConstraint(
            model_name='votomiembro',
            constraint=models.UniqueConstraint(fields=('miembro', 'partida_pregunta'), name='tf_un_voto_por_miembro_y_pregunta'),
        ),
    ]
