# Generated by Django 5.1.6 on 2026-08-04 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculadora', '0045_bluedollarrate_personalexpensecategory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReplyRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('palabra_clave', models.CharField(blank=True, help_text='Se dispara si el mensaje entrante CONTIENE este texto (sin mayúsculas/minúsculas). Vacío si es la regla de respaldo.', max_length=100)),
                ('respuesta', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('prioridad', models.PositiveIntegerField(default=0, help_text='Se evalúan de menor a mayor; la primera que matchee gana.')),
                ('es_fallback', models.BooleanField(default=False, help_text='Se usa cuando ningún otro palabra clave matchea. Solo debería haber una activa.')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['prioridad', 'id'],
            },
        ),
        migrations.CreateModel(
            name='BroadcastCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('template_name', models.CharField(help_text='Debe coincidir exactamente con una plantilla ya APROBADA en Meta', max_length=150)),
                ('template_language', models.CharField(default='es', max_length=10)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviando', 'Enviando'), ('enviado', 'Enviado'), ('error', 'Con errores')], default='borrador', max_length=20)),
                ('estado_objetivo', models.CharField(blank=True, choices=[('nuevo', 'Nuevo'), ('interesado', 'Interesado'), ('cliente', 'Cliente'), ('descartado', 'Descartado')], help_text='Filtra los contactos a los que se les envía por su estado. Vacío = todos.', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('enviado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wa_id', models.CharField(help_text="Número de teléfono en formato WhatsApp (sin '+', ej. 51987654321)", max_length=32, unique=True)),
                ('nombre_perfil', models.CharField(blank=True, help_text='Nombre que reporta WhatsApp para este contacto', max_length=150)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('interesado', 'Interesado'), ('cliente', 'Cliente'), ('descartado', 'Descartado')], default='nuevo', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ultimo_mensaje_en', models.DateTimeField(blank=True, null=True)),
                ('cliente_perfil', models.ForeignKey(blank=True, help_text='Vínculo manual con el perfil de cliente del sitio (opcional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contactos_whatsapp', to='calculadora.clienteperfil')),
            ],
            options={
                'ordering': ['-ultimo_mensaje_en', '-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(choices=[('in', 'Entrante'), ('out', 'Saliente')], max_length=3)),
                ('cuerpo', models.TextField(blank=True)),
                ('wa_message_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('es_automatico', models.BooleanField(default=False)),
                ('error_detalle', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='whatsapp_bot.contact')),
            ],
            options={
                'ordering': ['creado_en'],
            },
        ),
        migrations.CreateModel(
            name='CampaignRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('enviado', 'Enviado'), ('error', 'Error')], default='pendiente', max_length=20)),
                ('wa_message_id', models.CharField(blank=True, max_length=100)),
                ('error_detalle', models.TextField(blank=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatarios', to='whatsapp_bot.broadcastcampaign')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanas_recibidas', to='whatsapp_bot.contact')),
            ],
            options={
                'unique_together': {('campaign', 'contact')},
            },
        ),
    ]
