"""
Django settings for mi_sitio_web project.
Generated by 'django-admin startproject' using Django 5.1.
"""

from pathlib import Path
import os
import dj_database_url  # Asegúrate de tener este import si no lo tienes

from dotenv import load_dotenv
load_dotenv()


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# SECRET KEY
SECRET_KEY = os.environ.get('SECRET_KEY', 'default-secret-key')

# DEBUG (⚠️ Desactivá en producción)
DEBUG = True  # Cambiá a False en producción

# ALLOWED HOSTS (🛡️ Agregá dominios autorizados)
ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'www.invertiresfacil.com', 'invertiresfacil.com',
]
CSRF_TRUSTED_ORIGINS = [
    'https://www.invertiresfacil.com',
    'https://invertiresfacil.com',
]


# ===============================
# 🔒 Seguridad para producción
# ===============================

SECURE_SSL_REDIRECT = True              # 🔁 Redirige todo HTTP → HTTPS automáticamente
SESSION_COOKIE_SECURE = True           # 🍪 Solo envía cookies de sesión si la conexión es HTTPS
CSRF_COOKIE_SECURE = True              # 🛡️ Igual que arriba, pero para protección CSRF
ACCOUNT_DEFAULT_HTTP_PROTOCOL = "https"
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_HSTS_SECONDS = 31536000         # 📅 Obliga HTTPS por 1 año (usa menos en pruebas)
SECURE_HSTS_INCLUDE_SUBDOMAINS = True  # 🌐 Aplica HSTS también a subdominios
SECURE_HSTS_PRELOAD = True             # 📦 Permite incluir tu dominio en listas de HSTS preload
SECURE_BROWSER_XSS_FILTER = True       # 🧹 Evita algunos ataques XSS
SECURE_CONTENT_TYPE_NOSNIFF = True     # 🧪 Evita que los navegadores detecten tipos MIME incorrectos
X_FRAME_OPTIONS = 'DENY'               # ❌ Previene que tu sitio sea embebido (clickjacking)
# Nota: desactivá esto si usás iframes legítimos (como formularios de terceros)

# ===============================

# Aplicaciones instaladas
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'calculadora',
    'django.contrib.sites',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
    
]
SITE_ID = 2
AUTHENTICATION_BACKENDS = (
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
)


LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

ACCOUNT_EMAIL_VERIFICATION = "none"
ACCOUNT_AUTHENTICATION_METHOD = 'email'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_EMAIL_VERIFICATION = 'none'  # ya configurado
ACCOUNT_USERNAME_REQUIRED = False
SOCIALACCOUNT_QUERY_EMAIL = True


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'allauth.account.middleware.AccountMiddleware'
    

]

ROOT_URLCONF = 'mi_sitio_web.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            os.path.join(BASE_DIR, 'templates'),
            os.path.join(BASE_DIR, 'calculadora', 'templates', 'calculadora')
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',                
                ],
        },
    },
]

WSGI_APPLICATION = 'mi_sitio_web.wsgi.application'
import dj_database_url
import os

# Base de datos
if os.getenv('DJANGO_PRODUCTION') is None:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': dj_database_url.config(conn_max_age=600, ssl_require=True)
    }


# Validadores de contraseña
AUTH_PASSWORD_VALIDATORS = [
    {'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator'},
    {'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator'},
    {'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator'},
    {'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator'},
]

# Internacionalización
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# Archivos estáticos
STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / "static"]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATIC_TMP = os.path.join(BASE_DIR, 'static')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Sesiones en cookies (no en base de datos)
SESSION_ENGINE = "django.contrib.sessions.backends.signed_cookies"
SESSION_COOKIE_AGE = 86400
SESSION_SAVE_EVERY_REQUEST = True
SESSION_EXPIRE_AT_BROWSER_CLOSE = False

# ========================
# 🔐 MercadoPago settings
# ========================
import os

# Clave pública para el frontend (usada por JS)
MERCADOPAGO_PUBLIC_KEY = "APP_USR-d50447a1-443a-47e7-aeb8-93bfbdb34bb3"

# Access token para el backend (servidor)
# ✅ En producción se toma de variable de entorno
# ✅ En desarrollo local podés dejarlo directo para evitar problemas
MERCADOPAGO_ACCESS_TOKEN = os.getenv("MERCADOPAGO_ACCESS_TOKEN", "APP_USR-6668420399502504-041417-5a8482f6cec2c22853b53c7d1a71c063-36466013")
