# Guardá este archivo en:
# calculadora/management/commands/cargar_preguntas_quiz.py
#
# Asegurate de que existan los __init__.py vacíos en:
#   calculadora/management/__init__.py
#   calculadora/management/commands/__init__.py
#
# Luego corré:
#   python manage.py cargar_preguntas_quiz           # solo carga preguntas nuevas
#   python manage.py cargar_preguntas_quiz --reset-all  # borra todo y recarga

from django.core.management.base import BaseCommand
from calculadora.models import QuizQuestion, QuizOption

PREGUNTAS = {
    'acciones': [
        {'text': '¿Qué representa una acción de una empresa?','opciones': [('Una parte proporcional de la propiedad de la empresa', True),('Un préstamo que le hacés a la empresa', False),('Un contrato de trabajo con la empresa', False),('Un bono emitido por el gobierno', False)]},
        {'text': '¿Qué indica el ratio P/E (Precio/Ganancia) de una acción?','opciones': [('Cuántos años de ganancias se necesitan para recuperar la inversión', True),('El porcentaje de ganancia anual garantizada', False),('La cantidad de acciones disponibles en el mercado', False),('El precio máximo que alcanzó la acción en el año', False)]},
        {'text': '¿Qué es un dividendo?','opciones': [('Una parte de las ganancias que la empresa distribuye a sus accionistas', True),('El costo de comprar una acción en bolsa', False),('La comisión que cobra el broker por operar', False),('El impuesto que se paga al vender acciones', False)]},
        {'text': '¿Qué se entiende por acción "Blue Chip"?','opciones': [('Acciones de empresas grandes, sólidas y con trayectoria probada', True),('Acciones de startups tecnológicas de alto riesgo', False),('Acciones que pagan los dividendos más altos del mercado', False),('Acciones de empresas en proceso de quiebra', False)]},
        {'text': '¿Qué es un mercado bajista (Bear Market)?','opciones': [('Una caída sostenida del mercado de más del 20%', True),('Un mercado con pocas operaciones diarias', False),('Un mercado donde solo operan inversores institucionales', False),('Una suba sostenida del mercado de más del 20%', False)]},
        {'text': '¿Qué es el mercado alcista (Bull Market)?','opciones': [('Una suba sostenida de precios de más del 20% desde mínimos', True),('Un mercado con alto volumen de operaciones', False),('Un mercado exclusivo para inversores calificados', False),('Una caída del mercado mayor al 10%', False)]},
        {'text': '¿Qué es la capitalización bursátil de una empresa?','opciones': [('El precio de la acción multiplicado por la cantidad de acciones en circulación', True),('El total de activos que posee la empresa', False),('Las ganancias anuales de la empresa', False),('El precio al que salió a bolsa originalmente', False)]},
        {'text': '¿Qué es el MERVAL?','opciones': [('El índice bursátil de referencia de la Bolsa de Buenos Aires', True),('Un fondo de inversión del Estado argentino', False),('El Mercado de Valores de América Latina', False),('Un tipo de bono del gobierno argentino', False)]},
        {'text': '¿Qué es un ADR (American Depositary Receipt)?','opciones': [('Un certificado que permite operar acciones extranjeras en bolsas de EE.UU.', True),('Un bono del Tesoro americano', False),('Un tipo de fondo indexado americano', False),('Una regulación de la SEC para inversores extranjeros', False)]},
        {'text': '¿Qué es el "short selling" (venta en corto)?','opciones': [('Vender acciones que no tenés para recomprarlas más baratas después', True),('Comprar acciones por un período muy corto de tiempo', False),('Vender acciones antes de que suban de precio', False),('Invertir en acciones de pequeña capitalización', False)]},
        {'text': '¿Qué es un "stop loss"?','opciones': [('Una orden para vender automáticamente si el precio cae a cierto nivel', True),('El máximo que puede subir una acción en un día', False),('El costo total de pérdidas de una empresa', False),('Una comisión adicional del broker', False)]},
        {'text': '¿Qué es un split de acciones?','opciones': [('Dividir cada acción en varias, reduciendo el precio unitario', True),('Fusionar varias acciones en una sola', False),('Retirar acciones del mercado para subirles el precio', False),('Emitir nuevas acciones para recaudar capital', False)]},
        {'text': '¿Qué mide el ROE (Return on Equity)?','opciones': [('La rentabilidad que genera la empresa con el capital de los accionistas', True),('El retorno total de una inversión incluyendo dividendos', False),('El rendimiento de los activos totales de la empresa', False),('La relación entre deuda y patrimonio neto', False)]},
        {'text': '¿Qué es el EPS (Earnings Per Share)?','opciones': [('La ganancia neta de la empresa dividida por la cantidad de acciones', True),('El precio de la acción dividido por sus ganancias', False),('El porcentaje de ganancias distribuidas como dividendo', False),('La diferencia entre precio de compra y venta', False)]},
        {'text': '¿Qué es el "dividend yield" (rendimiento por dividendo)?','opciones': [('El dividendo anual dividido por el precio actual de la acción', True),('El total de dividendos pagados en la historia de la empresa', False),('La frecuencia con que la empresa paga dividendos', False),('El crecimiento anual del dividendo', False)]},
        {'text': '¿Qué son las acciones de crecimiento (growth stocks)?','opciones': [('Acciones de empresas que reinvierten sus ganancias para expandirse', True),('Acciones que tienen el mayor dividendo del mercado', False),('Acciones de empresas con más de 100 años de historia', False),('Acciones con precio inferior al valor libro', False)]},
        {'text': '¿Qué son las acciones de valor (value stocks)?','opciones': [('Acciones que cotizan por debajo de su valor fundamental estimado', True),('Acciones de las empresas más grandes del mundo', False),('Acciones con el mayor volumen de operaciones diarias', False),('Acciones que garantizan una rentabilidad mínima', False)]},
        {'text': '¿Qué es la volatilidad de una acción?','opciones': [('La amplitud y frecuencia de las variaciones en su precio', True),('El volumen promedio de operaciones diarias', False),('La diferencia entre su precio máximo y mínimo histórico', False),('El número de accionistas que tiene la empresa', False)]},
        {'text': '¿Qué es el valor libro (book value) de una acción?','opciones': [('El patrimonio neto de la empresa dividido por las acciones en circulación', True),('El precio al que cotizó la acción cuando salió a bolsa', False),('El precio mínimo que pagó alguien por esa acción', False),('El valor de los activos físicos de la empresa', False)]},
        {'text': '¿Qué mide el EBITDA?','opciones': [('Las ganancias antes de intereses, impuestos, depreciación y amortización', True),('El precio justo de una acción según sus fundamentos', False),('El ratio entre precio y ventas de la empresa', False),('Las ganancias después de pagar todos los impuestos', False)]},
        {'text': '¿Qué diferencia a una acción preferida de una ordinaria?','opciones': [('Tiene prioridad en el cobro de dividendos pero suele no tener derecho a voto', True),('Tiene más derechos de voto en las asambleas de accionistas', False),('Es la que se compra primero en una IPO', False),('Es la que tiene mayor liquidez en el mercado', False)]},
        {'text': '¿Qué es el índice S&P 500?','opciones': [('Un índice que sigue las 500 empresas más grandes de EE.UU.', True),('Un fondo de inversión del gobierno americano', False),('El índice de las 500 empresas tecnológicas más grandes', False),('Un bono soberano americano a 500 días', False)]},
        {'text': '¿Qué es el índice Dow Jones?','opciones': [('Un índice que sigue 30 grandes empresas industriales de EE.UU.', True),('Un índice de los 500 mayores bancos del mundo', False),('El rendimiento promedio de los bonos americanos', False),('Un índice de materias primas globales', False)]},
        {'text': '¿Qué son las acciones cíclicas?','opciones': [('Acciones cuyo rendimiento sigue de cerca el ciclo económico', True),('Acciones que solo se pueden comprar en fechas específicas', False),('Acciones que pagan dividendos en forma trimestral', False),('Acciones que rotan entre diferentes sectores', False)]},
        {'text': '¿Qué es el margen de beneficio neto?','opciones': [('La ganancia neta dividida por los ingresos totales de la empresa', True),('La diferencia entre el precio de compra y venta de una acción', False),('El rendimiento total de una acción en un año', False),('El porcentaje de ganancias que se distribuyen como dividendo', False)]},
        {'text': '¿Qué es una OPV o IPO?','opciones': [('La primera vez que una empresa ofrece sus acciones al público en bolsa', True),('Una oferta especial de acciones solo para empleados', False),('Una operación de compra-venta entre grandes inversores', False),('Un tipo de fusión entre dos empresas', False)]},
        {'text': '¿Qué es la liquidez de una acción?','opciones': [('La facilidad para comprarla o venderla sin afectar significativamente su precio', True),('El dinero en efectivo que tiene la empresa en caja', False),('El porcentaje de acciones disponibles para la venta', False),('La capacidad de la empresa para pagar sus deudas', False)]},
        {'text': '¿Qué es el precio objetivo de una acción?','opciones': [('El precio estimado por analistas al que debería llegar en un período dado', True),('El precio máximo al que se puede comprar una acción', False),('El precio de salida de la acción en su IPO', False),('El precio mínimo garantizado por la empresa', False)]},
        {'text': '¿Qué es el volumen de operaciones de una acción?','opciones': [('La cantidad de acciones que se compraron y vendieron en un período', True),('El precio promedio al que se operó la acción en el día', False),('La cantidad de accionistas que operaron en el día', False),('El valor total de la empresa en bolsa', False)]},
        {'text': '¿Qué significa diversificar una cartera de acciones?','opciones': [('Invertir en diferentes empresas, sectores o mercados para reducir el riesgo', True),('Comprar muchas acciones de la misma empresa para bajar el costo promedio', False),('Vender acciones periódicamente para asegurar ganancias', False),('Invertir solo en acciones de alta capitalización', False)]},
    ],
    'matematica_financiera': [
        {'text': '¿Qué es el interés compuesto?','opciones': [('El interés que se calcula sobre el capital más los intereses acumulados', True),('El interés que se paga solo al final del período', False),('El interés que cobra el banco por préstamos personales', False),('La suma de todos los intereses pagados en un año', False)]},
        {'text': '¿Qué es la TNA (Tasa Nominal Anual)?','opciones': [('La tasa de interés anual sin considerar el efecto de la capitalización', True),('La tasa de interés real ajustada por inflación', False),('La tasa que incluye todos los costos del préstamo', False),('La tasa máxima que puede cobrar un banco', False)]},
        {'text': '¿Qué es la TEA (Tasa Efectiva Anual)?','opciones': [('La tasa que incorpora el efecto de la capitalización en el período', True),('La tasa de interés antes de impuestos', False),('La tasa que cobra el Banco Central a los bancos comerciales', False),('La tasa nominal dividida por 12 meses', False)]},
        {'text': 'Si invertís $100 a una tasa del 10% anual simple por 3 años, ¿cuánto recibís?','opciones': [('$130', True),('$133.10', False),('$121', False),('$110', False)]},
        {'text': '¿Qué es el VPN (Valor Presente Neto)?','opciones': [('El valor actual de los flujos de caja futuros descontados a una tasa dada', True),('El valor de la empresa en el mercado bursátil', False),('La ganancia total de una inversión sin considerar el tiempo', False),('El precio justo de un activo según sus ganancias', False)]},
        {'text': '¿Qué es la TIR (Tasa Interna de Retorno)?','opciones': [('La tasa a la que el Valor Presente Neto de una inversión es igual a cero', True),('La tasa de interés mínima para invertir en un proyecto', False),('El rendimiento promedio de los últimos 5 años de una cartera', False),('La tasa de inflación implícita en una inversión', False)]},
        {'text': '¿Qué es el "valor del dinero en el tiempo"?','opciones': [('$1 hoy vale más que $1 en el futuro porque puede invertirse y crecer', True),('El valor que pierde el dinero por la inflación', False),('El interés que cobran los bancos por guardar dinero', False),('La diferencia entre el precio de compra y de venta', False)]},
        {'text': 'Si la inflación es del 100% anual y tu inversión rinde el 80%, ¿cuál es tu resultado real?','opciones': [('Negativo, perdés poder adquisitivo', True),('El 20% positivo', False),('El 80% real', False),('Cero, ambas tasas se compensan', False)]},
        {'text': '¿Cómo se calcula la tasa real aproximada de una inversión?','opciones': [('Tasa nominal menos inflación', True),('Tasa nominal dividida por la inflación', False),('Inflación menos tasa nominal', False),('Tasa nominal multiplicada por la inflación', False)]},
        {'text': '¿Qué es la amortización de un préstamo?','opciones': [('El proceso de pagar gradualmente el capital e intereses de una deuda', True),('El costo total de un préstamo incluyendo todos los gastos', False),('La penalidad por cancelar un préstamo antes de tiempo', False),('El seguro obligatorio en un préstamo hipotecario', False)]},
        {'text': '¿Qué es el sistema francés de amortización?','opciones': [('Un sistema donde las cuotas son iguales pero varía la proporción capital/interés', True),('Un sistema donde las cuotas disminuyen con el tiempo', False),('Un sistema donde solo se pagan intereses hasta el final', False),('Un sistema exclusivo para préstamos hipotecarios', False)]},
        {'text': '¿Qué es el CFT (Costo Financiero Total)?','opciones': [('El costo real del crédito incluyendo todos los gastos y comisiones', True),('La tasa de interés pura de un préstamo', False),('El capital total más los intereses del período', False),('La penalidad por pago anticipado de un crédito', False)]},
        {'text': '¿Qué es la "Regla del 72"?','opciones': [('Dividir 72 por la tasa de interés para saber en cuántos años se duplica el capital', True),('La edad óptima para empezar a invertir', False),('El porcentaje máximo recomendado para invertir en acciones', False),('La cantidad de inversiones necesarias para diversificar correctamente', False)]},
        {'text': 'Si tu capital rinde el 12% anual, ¿en cuántos años aproximadamente se duplica?','opciones': [('6 años', True),('12 años', False),('3 años', False),('8 años', False)]},
        {'text': '¿Qué es el "costo de oportunidad"?','opciones': [('El beneficio que resignás al elegir una inversión sobre otra alternativa', True),('El costo total de una inversión incluyendo impuestos y comisiones', False),('La pérdida máxima posible en una inversión', False),('El interés que perdés por no invertir en plazo fijo', False)]},
        {'text': '¿Qué es el "drawdown" máximo de una inversión?','opciones': [('La caída máxima desde el punto más alto al más bajo en un período', True),('El retiro máximo permitido de un fondo de inversión', False),('La pérdida fiscal máxima deducible en un año', False),('El monto mínimo para invertir en un instrumento', False)]},
        {'text': '¿Qué es la tasa libre de riesgo?','opciones': [('El rendimiento de una inversión considerada sin riesgo, generalmente bonos del gobierno', True),('La tasa de interés que garantiza no perder dinero en términos nominales', False),('La tasa mínima que exigen los bancos para otorgar préstamos', False),('La tasa de inflación esperada para el próximo año', False)]},
        {'text': '¿Qué significa "capitalización mensual" en un plazo fijo?','opciones': [('Los intereses se calculan y se agregan al capital cada mes', True),('Solo podés retirar el dinero al final de cada mes', False),('El plazo mínimo de inversión es de un mes', False),('La tasa varía según el mes del año', False)]},
        {'text': '¿Cuál de estas frecuencias de capitalización genera más rendimiento con la misma tasa?','opciones': [('Capitalización diaria', True),('Capitalización mensual', False),('Capitalización trimestral', False),('Capitalización anual', False)]},
        {'text': '¿Qué es el "punto de equilibrio" (breakeven)?','opciones': [('El punto donde los ingresos igualan a los costos, sin ganancia ni pérdida', True),('El precio al que una acción deja de caer', False),('El momento en que una inversión recupera exactamente su valor inicial', False),('La tasa a la que una inversión cubre exactamente la inflación', False)]},
        {'text': '¿Qué mide el índice de Sharpe?','opciones': [('El rendimiento excedente por unidad de riesgo tomado', True),('La correlación entre dos activos financieros', False),('El rendimiento total de una cartera en un año', False),('La volatilidad de un activo comparada con el mercado', False)]},
        {'text': '¿Qué es el "dollar cost averaging" (DCA)?','opciones': [('Invertir montos fijos periódicos independientemente del precio del activo', True),('Comprar solo cuando el precio está en mínimos históricos', False),('Convertir pesos a dólares en cuotas mensuales', False),('Diversificar entre activos en dólares y en pesos', False)]},
        {'text': '¿Qué es el "rendimiento real" de una inversión?','opciones': [('El rendimiento nominal ajustado por la inflación del período', True),('El rendimiento garantizado por el instrumento financiero', False),('El rendimiento antes de comisiones e impuestos', False),('El rendimiento comparado con el índice del mercado', False)]},
        {'text': '¿Cuál es la diferencia entre interés simple y compuesto en el largo plazo?','opciones': [('El compuesto crece exponencialmente, el simple crece linealmente', True),('No hay diferencia significativa en plazos largos', False),('El simple siempre genera más porque no acumula riesgo', False),('El compuesto solo aplica a inversiones en moneda extranjera', False)]},
        {'text': '¿Qué es el "valor futuro" de una inversión?','opciones': [('El monto que tendrás después de un período aplicando una tasa de interés', True),('El precio al que podrás vender tu inversión en el futuro', False),('La inflación proyectada sobre tu capital inicial', False),('El valor ajustado por impuestos de una inversión', False)]},
        {'text': '¿Qué es una anualidad en finanzas?','opciones': [('Una serie de pagos iguales realizados a intervalos regulares de tiempo', True),('Un bono que paga intereses una sola vez al año', False),('Un seguro que cubre pérdidas anuales de inversión', False),('Un plazo fijo con vencimiento anual renovable', False)]},
        {'text': '¿Qué es la tasa de descuento en finanzas?','opciones': [('La tasa usada para calcular el valor actual de flujos de fondos futuros', True),('El porcentaje de reducción en el precio de un bono en el mercado', False),('La tasa que aplica el BCRA a los bancos comerciales', False),('El descuento por pago anticipado de una deuda', False)]},
        {'text': 'Si pedís un préstamo a TNA 60% con capitalización mensual, la TEA es:','opciones': [('Mayor al 60% anual', True),('Exactamente el 60%', False),('Menor al 60% anual', False),('Igual a 5% mensual exacto', False)]},
        {'text': '¿Qué es el "margen de seguridad" en inversiones (concepto de Benjamin Graham)?','opciones': [('La diferencia entre el precio de mercado y el valor intrínseco estimado de un activo', True),('El porcentaje de efectivo que se mantiene en una cartera', False),('La pérdida máxima tolerada antes de vender un activo', False),('El rendimiento adicional sobre la tasa libre de riesgo', False)]},
        {'text': '¿Qué representa la "beta" de una acción?','opciones': [('La sensibilidad del precio de la acción respecto a los movimientos del mercado', True),('El rendimiento esperado de la acción en el próximo año', False),('La diferencia entre el precio actual y el precio objetivo', False),('La correlación de la acción con el tipo de cambio', False)]},
    ],
    'fci_etf': [
        {'text': '¿Qué es un Fondo Común de Inversión (FCI)?','opciones': [('Un vehículo que agrupa el dinero de varios inversores para invertir en conjunto', True),('Un plazo fijo de largo plazo con tasa variable', False),('Un tipo de bono emitido por el Estado nacional', False),('Una cuenta de ahorro con rendimiento variable del banco', False)]},
        {'text': '¿Qué es un ETF (Exchange Traded Fund)?','opciones': [('Un fondo que cotiza en bolsa como si fuera una acción', True),('Un fondo exclusivo para inversores institucionales', False),('Un bono que se intercambia entre bancos centrales', False),('Una criptomoneda respaldada por activos físicos', False)]},
        {'text': '¿Qué ventaja principal tiene un ETF sobre un fondo activo tradicional?','opciones': [('Generalmente cobra comisiones de gestión mucho más bajas', True),('Garantiza un rendimiento mínimo anual al inversor', False),('Solo invierte en activos de bajo riesgo', False),('Permite retirar el dinero en cualquier momento sin costo', False)]},
        {'text': '¿Qué es la "cuotaparte" de un FCI?','opciones': [('La unidad de participación que representa tu porción del fondo', True),('El costo mínimo de entrada al fondo', False),('La comisión mensual de administración del fondo', False),('El período mínimo de permanencia en el fondo', False)]},
        {'text': '¿Qué tipo de FCI es el más conservador en Argentina?','opciones': [('FCI money market (mercado de dinero)', True),('FCI de acciones argentinas', False),('FCI de bonos high yield', False),('FCI de infraestructura', False)]},
        {'text': '¿Qué índice replica el ETF SPY?','opciones': [('El S&P 500', True),('Las 30 empresas del Dow Jones', False),('Las 100 empresas del NASDAQ', False),('El mercado de bonos americano', False)]},
        {'text': '¿Qué es el "expense ratio" (ratio de gastos) de un ETF?','opciones': [('El porcentaje anual que cobra el fondo por su gestión', True),('La comisión que cobra el broker por cada operación', False),('El rendimiento mínimo garantizado por el fondo', False),('La diferencia entre el precio de compra y venta del ETF', False)]},
        {'text': '¿Qué significa que un FCI tenga "horizonte de inversión largo"?','opciones': [('Está diseñado para inversiones de varios años y tolera mayor volatilidad', True),('Que no se puede retirar el dinero por mucho tiempo', False),('Que cobra comisiones más altas que los fondos de corto plazo', False),('Que solo invierte en instrumentos con vencimiento a largo plazo', False)]},
        {'text': '¿Qué es un FCI de "renta fija"?','opciones': [('Un fondo que invierte principalmente en bonos y títulos de deuda', True),('Un fondo que garantiza una tasa fija de retorno', False),('Un fondo sin riesgo de pérdida de capital', False),('Un fondo exclusivo para jubilados y pensionados', False)]},
        {'text': '¿Qué es un ETF inverso?','opciones': [('Un ETF diseñado para ganar cuando el índice que sigue baja', True),('Un ETF que replica índices internacionales desde Argentina', False),('Un ETF que compra activos y los vende en el corto plazo', False),('Un ETF con rendimiento garantizado por el emisor', False)]},
        {'text': '¿Qué es el "tracking error" de un ETF?','opciones': [('La desviación entre el rendimiento del ETF y el índice que replica', True),('El error administrativo en el registro de cuotapartes', False),('La diferencia entre el precio de apertura y cierre del ETF', False),('El porcentaje de pérdida máxima histórica del fondo', False)]},
        {'text': '¿Qué ETF permite invertir en tecnología americana?','opciones': [('QQQ (sigue el NASDAQ 100)', True),('SPY (sigue el S&P 500)', False),('GLD (sigue el precio del oro)', False),('TLT (bonos del Tesoro americano a largo plazo)', False)]},
        {'text': '¿En qué se diferencia un FCI "abierto" de uno "cerrado"?','opciones': [('El abierto permite suscripciones y rescates continuamente; el cerrado tiene cuotas fijas', True),('El abierto es para inversores minoristas, el cerrado para institucionales', False),('El abierto no tiene fecha de vencimiento; el cerrado sí siempre', False),('El abierto cobra menos comisiones que el cerrado', False)]},
        {'text': '¿Qué es el NAV (Net Asset Value) de un fondo?','opciones': [('El valor de los activos del fondo dividido por las cuotapartes en circulación', True),('El rendimiento neto del fondo en el último año', False),('El precio de mercado de una cuotaparte del fondo', False),('La ganancia neta del fondo después de impuestos', False)]},
        {'text': '¿Qué ventaja tiene invertir en un FCI vs. hacerlo directamente en acciones?','opciones': [('Accedés a diversificación con montos pequeños de inversión', True),('Obtenés rendimientos garantizados y sin riesgo', False),('Pagás menos impuestos que comprando acciones directamente', False),('El fondo te asegura superar al índice del mercado', False)]},
        {'text': '¿Qué es un FCI "money market" en Argentina?','opciones': [('Un fondo que invierte en instrumentos de muy corto plazo como plazos fijos y cauciones', True),('Un fondo que invierte exclusivamente en moneda extranjera', False),('Un fondo que replica el comportamiento del dólar', False),('Un plazo fijo con liquidez diaria garantizada por el BCRA', False)]},
        {'text': '¿Qué es el "benchmark" de un fondo de inversión?','opciones': [('El índice de referencia contra el que se compara el rendimiento del fondo', True),('El rendimiento mínimo que debe obtener el fondo por contrato', False),('El objetivo de rentabilidad prometido al inversor', False),('La tasa de inflación que el fondo debe obligatoriamente superar', False)]},
        {'text': '¿Qué significa que un ETF sea "apalancado" (leveraged)?','opciones': [('Que amplifica los movimientos del índice, generalmente al doble o triple', True),('Que usa deuda para pagar dividendos a los inversores', False),('Que invierte en empresas con alto nivel de endeudamiento', False),('Que cobra una comisión adicional por cada operación', False)]},
        {'text': '¿Qué diferencia a un "fondo activo" de un "fondo pasivo"?','opciones': [('El activo tiene gestores que eligen inversiones; el pasivo replica un índice', True),('El activo tiene mayor liquidez diaria que el pasivo', False),('El activo garantiza rendimientos; el pasivo no', False),('El activo cobra menos comisiones que el pasivo', False)]},
        {'text': '¿Por qué la mayoría de los fondos activos no supera al S&P 500 en el largo plazo?','opciones': [('Las comisiones más altas y la dificultad de superar consistentemente al mercado', True),('Porque invierten en activos más riesgosos que el S&P 500', False),('Porque están obligados a mantener un porcentaje en efectivo', False),('Porque el gobierno americano regula sus rendimientos máximos', False)]},
        {'text': '¿Qué ETF usarías para invertir en oro?','opciones': [('GLD', True),('QQQ', False),('SPY', False),('VTI', False)]},
        {'text': '¿Qué es la "duration" en un fondo de bonos?','opciones': [('La sensibilidad del precio del fondo ante cambios en las tasas de interés', True),('El plazo promedio hasta el vencimiento de los bonos en cartera', False),('La duración mínima de permanencia requerida en el fondo', False),('El tiempo que tarda en acreditarse el rescate', False)]},
        {'text': '¿Qué significa "riesgo de crédito" en un FCI de renta fija?','opciones': [('El riesgo de que el emisor de los bonos no pueda pagar', True),('El riesgo de que el fondo cierre y no puedas rescatar tus fondos', False),('El riesgo de que las comisiones del fondo aumenten', False),('El riesgo de que el gestor tome decisiones incorrectas', False)]},
        {'text': '¿Cuál es la principal diferencia entre rescatar un FCI y vender un ETF?','opciones': [('El ETF se vende en el mercado a precio de bolsa; el FCI se rescata al NAV del día', True),('No hay diferencia, ambos se liquidan al mismo precio', False),('El FCI es más rápido de liquidar que un ETF', False),('Los ETFs tienen un período mínimo de tenencia obligatorio', False)]},
        {'text': '¿Qué es el "rebalanceo" de un ETF o fondo indexado?','opciones': [('El ajuste periódico de la composición del fondo para mantener las proporciones del índice', True),('La redistribución de ganancias entre los inversores del fondo', False),('El cobro periódico de las comisiones de gestión', False),('La incorporación de nuevos inversores al fondo', False)]},
        {'text': '¿Qué es un "fondo de fondos"?','opciones': [('Un fondo que invierte en otros fondos en lugar de activos directamente', True),('Un fondo que permite invertir desde múltiples plataformas', False),('Un fondo con múltiples administradores independientes', False),('Un fondo que combina acciones y bonos en igual proporción', False)]},
        {'text': '¿Qué es el "perfil de riesgo" del inversor?','opciones': [('La tolerancia del inversor a soportar pérdidas temporales en su cartera', True),('La cantidad máxima de dinero que puede perder en un fondo', False),('La calificación crediticia asignada al fondo de inversión', False),('El nivel de experiencia del gestor del fondo', False)]},
        {'text': '¿Qué son las "comisiones de salida" en un FCI?','opciones': [('Un cargo que se descuenta al rescatar cuotapartes antes de cierto plazo', True),('Los gastos de administración anuales del fondo', False),('El impuesto que se paga al retirar ganancias del fondo', False),('La penalidad por no mantener el saldo mínimo', False)]},
        {'text': '¿Qué conviene para protegerse de la inflación argentina: un FCI money market o uno dolarizado?','opciones': [('Un FCI dolarizado o que invierte en activos en moneda extranjera', True),('Un FCI money market en pesos', False),('Un FCI de bonos del gobierno a tasa fija en pesos', False),('Ambos protegen igual contra la inflación', False)]},
        {'text': '¿Qué ETF replica el mercado accionario total de EE.UU.?','opciones': [('VTI (Vanguard Total Stock Market)', True),('SPY (solo las 500 más grandes)', False),('QQQ (solo tecnológicas)', False),('IWM (solo empresas pequeñas)', False)]},
    ],
    'internacional': [
        {'text': '¿Cuál es la moneda de reserva mundial por excelencia?','opciones': [('El dólar estadounidense (USD)', True),('El euro (EUR)', False),('El yen japonés (JPY)', False),('El franco suizo (CHF)', False)]},
        {'text': '¿Qué es la Reserva Federal (Fed)?','opciones': [('El banco central de los Estados Unidos', True),('El fondo de reservas del gobierno americano', False),('La institución que regula Wall Street', False),('El banco que financia el comercio internacional', False)]},
        {'text': '¿Qué es el FMI (Fondo Monetario Internacional)?','opciones': [('Un organismo que asiste a países con problemas en su balanza de pagos', True),('Un fondo de inversión privado internacional', False),('El banco de los bancos centrales del mundo', False),('Un tratado de libre comercio entre países', False)]},
        {'text': '¿Qué es la tasa "Fed Funds Rate"?','opciones': [('La tasa de interés de referencia que fija la Reserva Federal de EE.UU.', True),('La tasa que cobran los bancos americanos a sus clientes', False),('El rendimiento de los bonos del Tesoro americano a 10 años', False),('La tasa de inflación objetivo de la Fed', False)]},
        {'text': '¿Qué son los bonos del Tesoro americano (Treasuries)?','opciones': [('Títulos de deuda emitidos por el gobierno de EE.UU., considerados libre de riesgo', True),('Acciones emitidas por empresas americanas en el exterior', False),('Instrumentos de inversión del sistema de pensiones americano', False),('Bonos emitidos por la Reserva Federal', False)]},
        {'text': '¿Qué es el sistema SWIFT?','opciones': [('Un sistema de mensajería para transferencias bancarias internacionales', True),('Una criptomoneda usada por los bancos centrales', False),('Un tratado de libre comercio entre países desarrollados', False),('Un índice de mercados financieros globales', False)]},
        {'text': '¿Qué es el "carry trade"?','opciones': [('Pedir prestado en una moneda de baja tasa e invertir en una de alta tasa', True),('El transporte físico de divisas entre países', False),('Una estrategia de compra y venta de materias primas', False),('La diferencia entre el precio de compra y venta de una divisa', False)]},
        {'text': '¿Qué es el índice NASDAQ?','opciones': [('Un índice bursátil de EE.UU. con foco en empresas tecnológicas', True),('Un índice de todas las materias primas globales', False),('El principal índice de la Bolsa de Londres', False),('Un índice de bonos soberanos americanos', False)]},
        {'text': '¿Qué son los mercados emergentes?','opciones': [('Economías en desarrollo con crecimiento dinámico pero mayor riesgo', True),('Países que recién crearon su bolsa de valores', False),('Economías que dependen exclusivamente de exportaciones', False),('Países sin acceso al sistema financiero internacional', False)]},
        {'text': '¿Qué es el tipo de cambio "spot"?','opciones': [('El precio actual de una divisa para entrega inmediata', True),('El precio futuro acordado de una divisa', False),('El tipo de cambio oficial de un gobierno', False),('El precio promedio de una divisa durante el año', False)]},
        {'text': '¿Qué mide el índice Big Mac?','opciones': [('El poder adquisitivo relativo entre países usando el precio de una hamburguesa', True),('El costo de vida en diferentes ciudades del mundo', False),('La inflación global de los alimentos procesados', False),('El rendimiento de la industria de comida rápida', False)]},
        {'text': '¿Qué es un bono soberano?','opciones': [('Un título de deuda emitido por el gobierno de un país', True),('Un bono emitido por las empresas más grandes de un país', False),('Un instrumento garantizado por el oro de un banco central', False),('Un bono que solo puede comprar el FMI', False)]},
        {'text': '¿Qué es el "riesgo país"?','opciones': [('La sobretasa que paga un país sobre los bonos del Tesoro americano', True),('El nivel de inseguridad jurídica de un mercado', False),('La probabilidad de guerra o conflicto en una nación', False),('El déficit fiscal de un país como porcentaje del PBI', False)]},
        {'text': '¿Qué es el G20?','opciones': [('Un foro de las 20 economías más grandes del mundo', True),('Un tratado de libre comercio entre 20 países', False),('Un grupo de los 20 países con mayor deuda soberana', False),('Una alianza militar de naciones industrializadas', False)]},
        {'text': '¿Qué es el "default soberano"?','opciones': [('Cuando un país no puede pagar su deuda externa en tiempo y forma', True),('Cuando un país abandona su moneda local por el dólar', False),('Cuando el FMI interviene la economía de un país', False),('Cuando un banco central imprime dinero sin respaldo', False)]},
        {'text': '¿Qué son los "commodities"?','opciones': [('Materias primas o productos básicos que se comercian globalmente', True),('Acciones de empresas de producción masiva', False),('Bonos emitidos por países productores de materias primas', False),('Fondos de inversión en recursos naturales', False)]},
        {'text': '¿Qué es el "petrodólar"?','opciones': [('El sistema donde el petróleo se cotiza y vende en dólares americanos', True),('Una criptomoneda respaldada por reservas de petróleo', False),('El dólar que usan los países del Medio Oriente', False),('Un bono emitido por países productores de petróleo', False)]},
        {'text': '¿Qué es el mercado Forex?','opciones': [('El mercado global descentralizado de compra y venta de divisas', True),('La bolsa de comercio de Londres', False),('El mercado de futuros de Chicago', False),('Un sistema de pagos interbancario internacional', False)]},
        {'text': '¿Qué es la "devaluación" de una moneda?','opciones': [('La reducción del valor de la moneda local frente a otras divisas', True),('El aumento del tipo de cambio en términos nominales únicamente', False),('La pérdida de valor real del dinero por la inflación', False),('La decisión política de abandonar la moneda local', False)]},
        {'text': '¿Qué es la "apreciación" de una moneda?','opciones': [('El aumento del valor de una moneda respecto a otras divisas', True),('El ajuste del tipo de cambio oficial por inflación', False),('El aumento del precio del oro en una economía', False),('La revalorización de los activos en moneda local', False)]},
        {'text': '¿Qué son los "mercados frontera" (frontier markets)?','opciones': [('Economías menos desarrolladas que los mercados emergentes, con menor liquidez', True),('Los mercados que están próximos a convertirse en emergentes', False),('Los mercados financieros de países sin acceso al FMI', False),('Los mercados de materias primas de África y Asia central', False)]},
        {'text': '¿Qué es la "balanza comercial"?','opciones': [('La diferencia entre las exportaciones e importaciones de un país', True),('El total de la deuda externa de un país', False),('El estado de las cuentas del gobierno de un país', False),('El nivel de reservas del banco central', False)]},
        {'text': '¿Qué es el "quantitative easing" (QE)?','opciones': [('La compra masiva de activos por parte de un banco central para inyectar dinero', True),('El control de la cantidad de billetes en circulación', False),('La fijación de la tasa de interés en cero por decreto', False),('La emisión de bonos del gobierno para financiar el déficit', False)]},
        {'text': '¿Qué es la paridad del poder adquisitivo (PPA)?','opciones': [('Una teoría que compara el poder de compra entre países', True),('La diferencia entre el tipo de cambio oficial y el paralelo', False),('La inflación acumulada de un país en un año', False),('El precio del dólar en distintas economías emergentes', False)]},
        {'text': '¿Qué es una "currency board" o caja de conversión?','opciones': [('Un sistema donde la moneda local está respaldada 1 a 1 por una divisa extranjera', True),('Una cuenta bancaria en moneda extranjera regulada por el estado', False),('Una oficina de cambio de divisas regulada por el banco central', False),('Un mecanismo de control de capitales del gobierno', False)]},
        {'text': '¿Qué es el Banco Central Europeo (BCE)?','opciones': [('El banco central que gestiona la política monetaria de la zona euro', True),('El banco que financia proyectos de desarrollo en toda Europa', False),('Una institución privada que regula los bancos europeos', False),('El fondo de rescate de países europeos en crisis', False)]},
        {'text': '¿Qué es la "dolarización" de una economía?','opciones': [('Adoptar el dólar americano como moneda oficial reemplazando la moneda local', True),('Fijar el tipo de cambio al valor del dólar mediante una ley', False),('Obligar a los bancos a mantener reservas en dólares', False),('Prohibir el uso de la moneda local en transacciones importantes', False)]},
        {'text': '¿Qué es el BID (Banco Interamericano de Desarrollo)?','opciones': [('Un banco que financia proyectos de desarrollo en América Latina y el Caribe', True),('El banco central de los países del MERCOSUR', False),('Un fondo de inversión privado latinoamericano', False),('Un organismo regulador del comercio americano', False)]},
        {'text': '¿Cuál es la principal diferencia entre bonos de corto y largo plazo?','opciones': [('Los de largo plazo son más sensibles a cambios en la tasa de interés', True),('Los de corto plazo pagan más intereses por su mayor riesgo', False),('Los de largo plazo siempre tienen menor rendimiento', False),('No hay diferencia significativa en su comportamiento', False)]},
        {'text': '¿Qué es la "inflación importada"?','opciones': [('El aumento de precios locales provocado por el encarecimiento de productos del exterior', True),('La inflación que generan los productos importados al ingresar al país', False),('El efecto inflacionario de la devaluación sobre los bienes locales', False),('La inflación de países desarrollados que se traslada a emergentes', False)]},
    ],
    'argentina': [
        {'text': '¿Qué es el BCRA?','opciones': [('El Banco Central de la República Argentina, que regula la política monetaria', True),('El Banco de Crédito y Reservas Argentinas', False),('El organismo que recauda impuestos en Argentina', False),('El fondo de garantía de los depósitos bancarios', False)]},
        {'text': '¿Qué es el "cepo cambiario"?','opciones': [('Restricciones gubernamentales para comprar moneda extranjera', True),('El impuesto que se cobra al cambiar pesos por dólares', False),('El tipo de cambio oficial fijado por el Banco Central', False),('El límite de retiros en efectivo de los bancos', False)]},
        {'text': '¿Qué es el dólar MEP (o dólar Bolsa)?','opciones': [('El dólar que se obtiene comprando y vendiendo bonos en distintas monedas vía bolsa', True),('El dólar que venden los bancos para gastos de turismo', False),('El dólar que usa el gobierno para pagar importaciones', False),('El tipo de cambio del mercado informal o negro', False)]},
        {'text': '¿Qué es el dólar "blue"?','opciones': [('El tipo de cambio del mercado informal o paralelo', True),('El dólar para compras en el exterior con tarjeta de crédito', False),('El dólar que otorga el Banco Central para viajes', False),('El dólar de las transacciones bursátiles reguladas', False)]},
        {'text': '¿Qué es el IPC (Índice de Precios al Consumidor)?','opciones': [('El indicador que mide la variación de precios de una canasta de bienes y servicios', True),('El índice que mide la producción industrial del país', False),('El indicador del nivel de pobreza en Argentina', False),('El índice de precios de los productos exportados', False)]},
        {'text': '¿Qué son los bonos UVA en Argentina?','opciones': [('Instrumentos que ajustan su capital por la inflación (Unidad de Valor Adquisitivo)', True),('Bonos del gobierno que pagan directamente en dólares', False),('Títulos de deuda emitidos por las provincias argentinas', False),('Instrumentos que ajustan por el tipo de cambio oficial', False)]},
        {'text': '¿Qué es el plazo fijo UVA?','opciones': [('Un depósito que ajusta por inflación más una tasa adicional', True),('Un plazo fijo en dólares con tasa variable', False),('Un depósito garantizado por el Estado con tasa fija en pesos', False),('Un instrumento de ahorro indexado al tipo de cambio oficial', False)]},
        {'text': '¿Qué es la AFIP?','opciones': [('El organismo recaudador de impuestos del Estado argentino', True),('El fondo de pensiones y jubilaciones del gobierno', False),('La agencia federal que regula los bancos comerciales', False),('El organismo de control del comercio exterior', False)]},
        {'text': '¿Qué es el ANSES?','opciones': [('La Administración Nacional de la Seguridad Social, que paga jubilaciones y asignaciones', True),('La agencia nacional de seguros del Estado', False),('El organismo que regulaba las AFJP', False),('El fondo nacional de sustentabilidad económica', False)]},
        {'text': '¿Qué son las Leliqs?','opciones': [('Letras de liquidez que emite el BCRA para que los bancos depositen sus excedentes', True),('Los préstamos que otorga el BCRA a los bancos comerciales', False),('Los bonos del Tesoro Nacional de muy corto plazo', False),('Los títulos que emite el gobierno para financiar el déficit fiscal', False)]},
        {'text': '¿Qué es el déficit fiscal?','opciones': [('Cuando el Estado gasta más de lo que recauda en impuestos y otros ingresos', True),('Cuando el BCRA emite más dinero del que la economía demanda', False),('La diferencia negativa entre exportaciones e importaciones', False),('El atraso del tipo de cambio respecto a la inflación acumulada', False)]},
        {'text': '¿Qué fue la convertibilidad en Argentina?','opciones': [('Un régimen cambiario que fijó el peso al dólar a 1 a 1 entre 1991 y 2001', True),('El proceso de dolarización total de la economía en 2001', False),('La reforma que creó el peso argentino como moneda nacional', False),('Un programa de préstamos del FMI aplicado durante los años 90', False)]},
        {'text': '¿Qué es el "corralito" en la historia financiera argentina?','opciones': [('La restricción al retiro de depósitos bancarios aplicada en diciembre de 2001', True),('El nombre popular del cepo cambiario implementado en 2011', False),('El programa de congelamiento de precios de los años 80', False),('El control de cambios aplicado durante la pandemia de COVID-19', False)]},
        {'text': '¿Qué es el dólar "contado con liquidación" (CCL)?','opciones': [('El dólar obtenido comprando activos locales y vendiéndolos en el exterior', True),('El dólar que se usa para pagos con tarjeta en el exterior', False),('El tipo de cambio de las importaciones de bienes especiales', False),('El dólar que paga el gobierno por su deuda externa', False)]},
        {'text': '¿Qué es la brecha cambiaria en Argentina?','opciones': [('La diferencia porcentual entre el tipo de cambio oficial y los tipos alternativos', True),('El impuesto que se aplica al cambio de divisas en los bancos', False),('La diferencia entre el precio de compra y venta en el banco', False),('El atraso cambiario acumulado en un año calendario', False)]},
        {'text': '¿Qué es el "impuesto PAIS"?','opciones': [('Un impuesto sobre compras en moneda extranjera aplicado en Argentina', True),('El impuesto al patrimonio de los argentinos con activos en el exterior', False),('El gravamen sobre las importaciones de bienes de lujo', False),('Un impuesto sobre los ingresos de personas no residentes', False)]},
        {'text': '¿Qué es la CNV en Argentina?','opciones': [('La Comisión Nacional de Valores, que regula el mercado de capitales', True),('La Confederación Nacional de Vendedores', False),('El organismo que controla el precio de los alimentos', False),('La entidad que autoriza la emisión de billetes', False)]},
        {'text': '¿Qué son las "retenciones" en Argentina?','opciones': [('Impuestos a las exportaciones, principalmente agropecuarias', True),('Los descuentos del sueldo para jubilación y obra social', False),('Los impuestos que se retienen en los pagos a profesionales', False),('Las comisiones que cobra la AFIP sobre las importaciones', False)]},
        {'text': '¿Qué es el INDEC?','opciones': [('El Instituto Nacional de Estadística y Censos, que mide variables económicas', True),('El organismo nacional de desarrollo y crecimiento económico', False),('El índice de desarrollo económico y comercial del país', False),('La entidad que controla precios e inflación directamente', False)]},
        {'text': '¿Qué son los "Pases" del BCRA?','opciones': [('Operaciones de corto plazo donde los bancos depositan o toman fondos del BCRA', True),('Los títulos que emite el Tesoro para financiar el déficit', False),('Las transferencias de fondos entre el BCRA y el Tesoro Nacional', False),('Los préstamos del FMI desembolsados por tramos', False)]},
        {'text': '¿Qué fue el "Plan Austral" de 1985?','opciones': [('Un plan de estabilización que creó el austral como nueva moneda para frenar la inflación', True),('El plan económico que dolarizó parcialmente la economía argentina', False),('La reforma financiera que creó el BCRA en su forma moderna', False),('El programa del FMI aplicado durante el gobierno militar', False)]},
        {'text': '¿Qué son los bonos dolarizados argentinos (como el AL30)?','opciones': [('Bonos del Estado argentino que pagan en dólares o su equivalente en pesos', True),('Bonos del Estado americano disponibles para compradores argentinos', False),('Certificados de depósito en dólares en bancos argentinos', False),('Instrumentos del BCRA para captar divisas del público', False)]},
        {'text': '¿Qué es el "crawling peg" o tablita cambiaria?','opciones': [('Un sistema de devaluaciones graduales y predeterminadas del tipo de cambio', True),('Una tabla de tipos de cambio diferenciados por sector económico', False),('El acuerdo de tipo de cambio fijo negociado con el FMI', False),('El sistema de bandas cambiarias usado en los años 90', False)]},
        {'text': '¿Qué es el "riesgo país" de Argentina?','opciones': [('La sobretasa en puntos básicos que Argentina paga sobre los bonos del Tesoro de EE.UU.', True),('La probabilidad de default calculada por las calificadoras de riesgo', False),('El nivel de incertidumbre política del país medido por encuestas', False),('El índice de seguridad jurídica para inversores extranjeros', False)]},
        {'text': '¿Qué es el "superávit gemelo" en economía?','opciones': [('Superávit fiscal y superávit de cuenta corriente de la balanza de pagos al mismo tiempo', True),('El excedente simultáneo de reservas y de la balanza comercial', False),('Dos años consecutivos de superávit fiscal primario', False),('Un indicador que combina ahorro público y privado positivos', False)]},
        {'text': '¿Qué fue el "blanqueo de capitales" en Argentina?','opciones': [('Un programa que permite declarar activos no registrados a cambio de una penalidad reducida', True),('El proceso de lavar dinero de origen ilícito a través del sistema financiero', False),('La conversión de pesos a dólares sin restricciones cambiarias', False),('Un beneficio impositivo exclusivo para exportadores del agro', False)]},
        {'text': '¿Qué fueron las AFJP en Argentina?','opciones': [('Administradoras privadas de fondos de jubilaciones y pensiones, existentes hasta 2008', True),('Las agencias federales de justicia patrimonial del BCRA', False),('Los fondos de inversión autorizados por la AFIP', False),('Las asociaciones federales de jubilados y pensionados', False)]},
        {'text': '¿Qué es la Bolsa de Comercio de Buenos Aires?','opciones': [('El mercado donde se negocian acciones, bonos y otros instrumentos en Argentina', True),('El organismo que regula el comercio exterior argentino', False),('La entidad pública que administra las reservas del BCRA', False),('El banco de inversión más grande de Argentina', False)]},
        {'text': '¿Qué dilema representa el ahorro en pesos vs. dólares para el inversor argentino?','opciones': [('El peso pierde valor por inflación; el dólar protege pero tiene riesgos regulatorios', True),('Ambas opciones son equivalentes en el largo plazo', False),('Los pesos siempre rinden más que el dólar en Argentina', False),('El dólar no tiene ningún riesgo y siempre es la mejor opción', False)]},
        {'text': '¿Qué es la "emisión monetaria" y por qué preocupa en Argentina?','opciones': [('La creación de dinero por parte del BCRA, que genera inflación si es excesiva', True),('La impresión de billetes de alta denominación para el ahorro', False),('La compra de dólares por parte del BCRA con reservas', False),('El proceso de crear nuevos bonos del Tesoro Nacional', False)]},
    ],
    'fintech': [
        {'text': '¿Qué es una empresa Fintech?','opciones': [('Una empresa tecnológica que ofrece servicios financieros de forma digital', True),('Un tipo de fondo de inversión en empresas tecnológicas', False),('Una empresa de tecnología que cotiza en bolsa', False),('Un banco digital sin ningún tipo de regulación', False)]},
        {'text': '¿Qué es el blockchain?','opciones': [('Una base de datos distribuida e inmutable organizada en bloques encadenados', True),('Un tipo de cifrado bancario internacional', False),('El sistema operativo de las criptomonedas', False),('Una red privada de transferencias bancarias', False)]},
        {'text': '¿Qué es Bitcoin?','opciones': [('Una criptomoneda descentralizada creada en 2009 por Satoshi Nakamoto', True),('Un sistema de pagos creado por el gobierno americano', False),('Una moneda digital emitida por el Banco Mundial', False),('Un token de acceso a servicios financieros online', False)]},
        {'text': '¿Qué es una "stablecoin"?','opciones': [('Una criptomoneda diseñada para mantener un valor estable, generalmente vinculada al dólar', True),('Una criptomoneda con baja volatilidad por su tecnología avanzada', False),('Un token emitido directamente por bancos centrales', False),('Una criptomoneda respaldada por oro físico en bóvedas', False)]},
        {'text': '¿Qué es el USDT (Tether)?','opciones': [('Una stablecoin cuyo valor está vinculado al dólar americano 1 a 1', True),('Una criptomoneda creada por el gobierno americano', False),('Un token de utilidad de la red Ethereum', False),('Una moneda digital del Banco de Inglaterra', False)]},
        {'text': '¿Qué es DeFi (Finanzas Descentralizadas)?','opciones': [('Un ecosistema financiero basado en blockchain que opera sin intermediarios tradicionales', True),('Un fondo de inversión en empresas tecnológicas descentralizadas', False),('Un protocolo de seguridad para transacciones online', False),('Un sistema de pagos entre bancos que evita usar SWIFT', False)]},
        {'text': '¿Qué es una billetera cripto (wallet)?','opciones': [('Un software que almacena las claves privadas para acceder a tus criptomonedas', True),('Una cuenta bancaria digital para guardar criptomonedas', False),('Un exchange donde se compran y venden criptomonedas', False),('Una tarjeta de débito vinculada a criptoactivos', False)]},
        {'text': '¿Qué es Mercado Pago?','opciones': [('Una plataforma de pagos digitales y servicios financieros de MercadoLibre', True),('El sistema de pagos digitales del Banco Central argentino', False),('Una red de cajeros automáticos virtuales', False),('Una aplicación exclusiva para pagos internacionales', False)]},
        {'text': '¿Qué es el "Open Banking"?','opciones': [('Un sistema que permite compartir datos bancarios con terceros autorizados por el cliente', True),('Una regulación que obliga a los bancos a abrir sucursales digitales', False),('El proceso de abrir cuentas bancarias de forma 100% online', False),('Un sistema de banca sin comisiones de mantenimiento de cuenta', False)]},
        {'text': '¿Qué es un "exchange" de criptomonedas?','opciones': [('Una plataforma donde se compran, venden e intercambian criptomonedas', True),('La bolsa de valores donde cotizan las empresas del sector cripto', False),('Un protocolo para intercambiar tokens entre distintas blockchains', False),('Una entidad reguladora del mercado de criptomonedas', False)]},
        {'text': '¿Qué es el "mining" (minería) de criptomonedas?','opciones': [('El proceso computacional de validar transacciones y generar nuevas unidades de cripto', True),('La extracción de metales preciosos con tecnología blockchain', False),('El análisis de datos para predecir precios de criptomonedas', False),('La creación de nuevas criptomonedas por startups tecnológicas', False)]},
        {'text': '¿Qué es un NFT (Non-Fungible Token)?','opciones': [('Un token único en blockchain que certifica la propiedad de un activo digital', True),('Una criptomoneda no intercambiable por otras divisas', False),('Un contrato inteligente entre dos partes en la blockchain', False),('Un tipo de stablecoin emitida por creadores de contenido', False)]},
        {'text': '¿Qué es un "smart contract" (contrato inteligente)?','opciones': [('Un programa autoejectable en blockchain que cumple condiciones automáticamente', True),('Un contrato legal digital firmado con firma electrónica', False),('Un acuerdo regulado entre dos exchanges de criptomonedas', False),('Un sistema de pagos automáticos entre empresas vía banco', False)]},
        {'text': '¿Qué es Ethereum?','opciones': [('Una plataforma blockchain que permite crear contratos inteligentes y aplicaciones descentralizadas', True),('La segunda criptomoneda más antigua después de Bitcoin', False),('Un protocolo de pagos creado por el MIT', False),('Una empresa tecnológica que emite su propia criptomoneda', False)]},
        {'text': '¿Qué es el "gas fee" en la red Ethereum?','opciones': [('La comisión que se paga a los validadores por procesar transacciones en Ethereum', True),('El costo energético del proceso de minería de Ethereum', False),('La tarifa de conversión entre Ethereum y Bitcoin', False),('El impuesto que cobra el gobierno sobre transacciones cripto', False)]},
        {'text': '¿Qué es la "seed phrase" (frase semilla)?','opciones': [('Una serie de 12 o 24 palabras que permiten recuperar el acceso a una billetera cripto', True),('La contraseña principal encriptada de una billetera digital', False),('El código QR asociado a una dirección de billetera cripto', False),('El número de serie único de una billetera hardware', False)]},
        {'text': '¿Qué es el "halving" de Bitcoin?','opciones': [('La reducción a la mitad de la recompensa por minar un bloque de Bitcoin', True),('Una caída del precio de Bitcoin superior al 50%', False),('La división de Bitcoin en dos criptomonedas distintas', False),('El proceso de quemar la mitad de los Bitcoins en circulación', False)]},
        {'text': '¿Qué es una CBDC (Central Bank Digital Currency)?','opciones': [('Una moneda digital emitida y respaldada por un banco central', True),('Una criptomoneda descentralizada avalada por gobiernos', False),('Un tipo de stablecoin regulada internacionalmente', False),('Un token que representa las reservas del banco central', False)]},
        {'text': '¿Qué es el "phishing" en el contexto financiero digital?','opciones': [('Un fraude donde se engaña al usuario para robar sus credenciales o datos', True),('Un tipo de ataque que roba fondos directamente de la blockchain', False),('Una técnica para clonar tarjetas de crédito físicas', False),('Un software malicioso que mina criptomonedas sin el permiso del dueño', False)]},
        {'text': '¿Qué es una DEX (Decentralized Exchange)?','opciones': [('Un exchange de criptomonedas que opera sin intermediarios centralizados', True),('Un exchange regulado por un gobierno nacional', False),('Un protocolo de intercambio entre distintas blockchains', False),('Una plataforma de trading exclusiva para inversores institucionales', False)]},
        {'text': '¿Qué es el "yield farming" en DeFi?','opciones': [('Proveer liquidez a protocolos DeFi a cambio de rendimientos o tokens', True),('Una estrategia de inversión en acciones de empresas agrícolas', False),('El proceso de crear nuevas criptomonedas en una blockchain', False),('Un sistema de ahorro descentralizado sin ningún tipo de riesgo', False)]},
        {'text': '¿Qué es un "rugpull" en el mundo cripto?','opciones': [('Cuando los creadores de un proyecto crypto lo abandonan y se llevan los fondos', True),('Una caída brusca y natural del precio de una criptomoneda', False),('Un ataque de hackers a un exchange centralizado', False),('El proceso legal de cerrar y liquidar un protocolo DeFi', False)]},
        {'text': '¿Qué son las soluciones "Layer 2" en blockchain?','opciones': [('Redes construidas sobre una blockchain principal para mejorar velocidad y reducir costos', True),('Las blockchains de segunda generación como Ethereum', False),('Los nodos secundarios que validan transacciones en la red', False),('Las capas de seguridad adicionales de una billetera hardware', False)]},
        {'text': '¿Qué es la "dominancia de Bitcoin"?','opciones': [('El porcentaje del mercado cripto total que representa la capitalización de Bitcoin', True),('La cantidad de países donde Bitcoin es moneda de curso legal', False),('El porcentaje de transacciones globales realizadas en Bitcoin', False),('La participación de Bitcoin en el PIB mundial', False)]},
        {'text': '¿Qué es el "staking" de criptomonedas?','opciones': [('Bloquear criptomonedas para apoyar la operación de una red y recibir recompensas', True),('Minar criptomonedas usando únicamente energía solar', False),('Guardar criptomonedas en una billetera fría por un tiempo determinado', False),('Intercambiar criptomonedas en un exchange descentralizado', False)]},
        {'text': '¿Qué es una "cold wallet" (billetera fría)?','opciones': [('Un dispositivo físico que almacena claves privadas sin conexión a internet', True),('Una billetera cripto que no tiene fondos activos en este momento', False),('Una cuenta inactiva en un exchange de criptomonedas', False),('Un software de billetera con cifrado adicional de alta seguridad', False)]},
        {'text': '¿Qué es la "tokenización" de activos?','opciones': [('Representar activos del mundo real como inmuebles o arte como tokens en blockchain', True),('El proceso de crear nuevas criptomonedas desde cero', False),('La conversión de criptomonedas a moneda fiduciaria', False),('El intercambio de tokens entre distintas blockchains', False)]},
        {'text': '¿Qué es Binance?','opciones': [('El exchange de criptomonedas con mayor volumen de operaciones del mundo', True),('El creador de la plataforma Ethereum', False),('El banco digital más grande de Asia', False),('La empresa que emitió la primera stablecoin', False)]},
        {'text': '¿Qué es el "FOMO" en el contexto de inversiones en cripto?','opciones': [('El miedo a quedarse afuera de una oportunidad de inversión (Fear Of Missing Out)', True),('La estrategia de seguir las tendencias del mercado sin análisis propio', False),('Un indicador técnico de sobrecompra en el mercado cripto', False),('Un tipo de fraude donde se infla artificialmente el precio de un activo', False)]},
        {'text': '¿Qué es el "pump and dump" en mercados de cripto?','opciones': [('Inflar artificialmente el precio de un activo para luego vender y dejarlo caer', True),('Una estrategia legítima de compra en mínimos y venta en máximos', False),('Un tipo de fraude exclusivo de los mercados accionarios', False),('El proceso de emitir y luego retirar tokens del mercado', False)]},
    ],
}


class Command(BaseCommand):
    help = 'Carga 180 preguntas del quiz financiero (30 por categoría)'

    def add_arguments(self, parser):
        parser.add_argument(
            '--reset-all',
            action='store_true',
            help='Elimina TODAS las preguntas antes de cargar',
        )

    def handle(self, *args, **options):
        if options.get('reset_all'):
            deleted, _ = QuizQuestion.objects.all().delete()
            self.stdout.write(self.style.WARNING(f'Eliminadas {deleted} preguntas.'))
        else:
            legacy = QuizQuestion.objects.filter(categoria='')
            n = legacy.count()
            if n:
                legacy.delete()
                self.stdout.write(self.style.WARNING(f'Eliminadas {n} preguntas legacy sin categoría.'))

        total = 0
        for categoria, preguntas in PREGUNTAS.items():
            existentes = set(QuizQuestion.objects.filter(categoria=categoria).values_list('text', flat=True))
            nuevas = 0
            for p in preguntas:
                if p['text'] in existentes:
                    continue
                q = QuizQuestion.objects.create(text=p['text'], categoria=categoria)
                for texto, correcta in p['opciones']:
                    QuizOption.objects.create(question=q, text=texto, is_correct=correcta)
                nuevas += 1
            total += nuevas
            self.stdout.write(self.style.SUCCESS(f'  [{categoria}] → {nuevas} nuevas'))

        self.stdout.write(self.style.SUCCESS(f'\n🎉 {total} preguntas cargadas. Usá --reset-all para borrar todo y recargar.'))