"""Banco de preguntas de educación financiera para secundario.

Cada pregunta: texto, 4 opciones, índice de la correcta (0-3), explicación breve,
dificultad y categoría. Se cargan vía el management command `seed_preguntas`.
"""

PREGUNTAS = [
    # --- FÁCIL ---
    {
        "texto": "¿Qué es un presupuesto personal?",
        "opciones": [
            "Un préstamo que te da el banco",
            "Un plan de cuánto vas a ganar y gastar en un período",
            "El total de tus ahorros",
            "Un impuesto que paga tu familia",
        ],
        "respuesta_correcta": 1,
        "explicacion": "Un presupuesto es organizar por anticipado tus ingresos y gastos.",
        "dificultad": "facil",
        "categoria": "presupuesto",
    },
    {
        "texto": "Si ganás $10.000 por mes y gastás $12.000, ¿qué está pasando?",
        "opciones": [
            "Estás ahorrando $2.000",
            "Estás en déficit: gastás más de lo que ganás",
            "Tenés superávit",
            "Nada, es normal siempre",
        ],
        "respuesta_correcta": 1,
        "explicacion": "Gastar más de lo que entra genera déficit, que se cubre con deuda o ahorros previos.",
        "dificultad": "facil",
        "categoria": "ahorro",
    },
    {
        "texto": "¿Qué es el interés en un préstamo?",
        "opciones": [
            "Un regalo del banco",
            "El costo que pagás por usar plata prestada",
            "La plata que ahorrás",
            "Un impuesto del gobierno",
        ],
        "respuesta_correcta": 1,
        "explicacion": "El interés es lo que le pagás a quien te prestó dinero, además de devolver lo prestado.",
        "dificultad": "facil",
        "categoria": "deuda_interes",
    },
    {
        "texto": "¿Para qué sirve principalmente un banco?",
        "opciones": [
            "Solo para guardar plata bajo llave",
            "Para guardar dinero, prestarlo y facilitar pagos",
            "Para imprimir billetes",
            "Para vender productos",
        ],
        "respuesta_correcta": 1,
        "explicacion": "Los bancos custodian dinero, otorgan préstamos y ofrecen medios de pago.",
        "dificultad": "facil",
        "categoria": "otros",
    },
    {
        "texto": "¿Cuál de estas es una buena razón para ahorrar?",
        "opciones": [
            "Tener un fondo para emergencias",
            "Porque no hay nada para comprar",
            "Para pagar más impuestos",
            "No sirve ahorrar",
        ],
        "respuesta_correcta": 0,
        "explicacion": "Un fondo de emergencia te protege ante imprevistos (gastos médicos, reparaciones, etc).",
        "dificultad": "facil",
        "categoria": "ahorro",
    },
    {
        "texto": "Un gasto 'fijo' es aquel que...",
        "opciones": [
            "Cambia todos los meses sin control",
            "Se repite todos los meses por un monto similar, como el alquiler",
            "Solo pasa una vez en la vida",
            "Es siempre el gasto más chico",
        ],
        "respuesta_correcta": 1,
        "explicacion": "Los gastos fijos (alquiler, cuotas) se repiten mes a mes, a diferencia de los variables.",
        "dificultad": "facil",
        "categoria": "presupuesto",
    },
    {
        "texto": "Si pedís prestado y no pagás a tiempo, generalmente...",
        "opciones": [
            "Te devuelven parte del dinero",
            "Se te suman intereses o multas por mora",
            "La deuda desaparece",
            "El banco te agradece",
        ],
        "respuesta_correcta": 1,
        "explicacion": "Pagar tarde casi siempre implica un costo extra (intereses moratorios).",
        "dificultad": "facil",
        "categoria": "deuda_interes",
    },
    # --- MEDIA ---
    {
        "texto": "¿Qué diferencia al interés compuesto del interés simple?",
        "opciones": [
            "El compuesto se calcula solo sobre el capital inicial",
            "El compuesto se calcula también sobre los intereses ya generados, no solo el capital inicial",
            "No hay ninguna diferencia real",
            "El interés simple siempre es más alto",
        ],
        "respuesta_correcta": 1,
        "explicacion": 'En el interés compuesto, los intereses generados se suman al capital y también generan intereses ("interés sobre interés").',
        "dificultad": "media",
        "categoria": "deuda_interes",
    },
    {
        "texto": "En general, ¿qué relación existe entre riesgo y retorno esperado de una inversión?",
        "opciones": [
            "A mayor riesgo, menor retorno esperado",
            "No tienen relación",
            "A mayor riesgo, generalmente mayor retorno potencial (y mayor posibilidad de pérdida)",
            "El riesgo no afecta las inversiones",
        ],
        "respuesta_correcta": 2,
        "explicacion": "Las inversiones más riesgosas suelen ofrecer mayor retorno potencial, pero también mayor probabilidad de pérdida.",
        "dificultad": "media",
        "categoria": "inversion_riesgo",
    },
    {
        "texto": "¿Qué significa 'diversificar' una inversión?",
        "opciones": [
            "Poner toda la plata en un solo activo para maximizar ganancias",
            "Repartir el dinero en distintos activos para reducir el riesgo",
            "Gastar toda la plata rápido",
            "Invertir solo en un banco",
        ],
        "respuesta_correcta": 1,
        "explicacion": "Diversificar reduce el riesgo porque no dependés del resultado de un solo activo.",
        "dificultad": "media",
        "categoria": "inversion_riesgo",
    },
    {
        "texto": "¿Qué es la inflación?",
        "opciones": [
            "La suba generalizada y sostenida de los precios",
            "La baja de precios",
            "El aumento del salario mínimo",
            "Un tipo de impuesto",
        ],
        "respuesta_correcta": 0,
        "explicacion": "La inflación es cuando, en general, los precios suben y el dinero pierde poder de compra.",
        "dificultad": "media",
        "categoria": "otros",
    },
    {
        "texto": "Si la inflación anual es del 100% y tus ahorros están guardados sin generar ningún rendimiento, ¿qué pasa con tu poder de compra?",
        "opciones": [
            "Se mantiene igual",
            "Aumenta",
            "Se reduce a la mitad aproximadamente",
            "Se duplica",
        ],
        "respuesta_correcta": 2,
        "explicacion": "Si los precios se duplican y tu dinero no crece, con la misma plata comprás la mitad de cosas.",
        "dificultad": "media",
        "categoria": "ahorro",
    },
    {
        "texto": "La regla 50/30/20 sugiere destinar tus ingresos aproximadamente a...",
        "opciones": [
            "50% gastos esenciales, 30% deseos, 20% ahorro o deudas",
            "50% ahorro, 30% gastos, 20% deudas",
            "100% gastos, 0% ahorro",
            "50% deudas, 50% gastos",
        ],
        "respuesta_correcta": 0,
        "explicacion": "Es una guía popular de presupuesto: mitad a necesidades, un tercio a gustos, y el resto a ahorro o pago de deudas.",
        "dificultad": "media",
        "categoria": "presupuesto",
    },
    {
        "texto": "¿Cuál de estas suele ser la deuda con la tasa de interés más alta para una persona común?",
        "opciones": [
            "Un préstamo hipotecario",
            "El saldo de una tarjeta de crédito no pagado a tiempo",
            "Un préstamo estudiantil estatal",
            "Ninguna deuda tiene tasa de interés",
        ],
        "respuesta_correcta": 1,
        "explicacion": "Las tarjetas de crédito suelen tener tasas de interés muy altas si no pagás el total a tiempo.",
        "dificultad": "media",
        "categoria": "deuda_interes",
    },
    # --- DIFÍCIL ---
    {
        "texto": "¿Qué es la 'liquidez' de una inversión?",
        "opciones": [
            "Que la inversión es en efectivo físico",
            "Qué tan rápido y fácil podés convertirla en dinero disponible sin perder mucho valor",
            "El interés que paga",
            "El riesgo que tiene",
        ],
        "respuesta_correcta": 1,
        "explicacion": "Un activo muy líquido (como una caja de ahorro) se convierte en efectivo rápido; un inmueble, por ejemplo, es poco líquido.",
        "dificultad": "dificil",
        "categoria": "inversion_riesgo",
    },
    {
        "texto": "Un préstamo tiene una TNA (Tasa Nominal Anual) del 60% pero una TEA (Tasa Efectiva Anual) del 79%. ¿Por qué son distintas?",
        "opciones": [
            "Es un error, deberían ser iguales",
            "La TEA incluye el efecto de la capitalización de intereses durante el año, la TNA no",
            "La TNA siempre es mayor que la TEA",
            "No tiene relación con el interés compuesto",
        ],
        "respuesta_correcta": 1,
        "explicacion": "La TEA refleja el costo real anual considerando cómo se acumulan los intereses en el tiempo; suele ser mayor que la TNA.",
        "dificultad": "dificil",
        "categoria": "deuda_interes",
    },
    {
        "texto": "¿Por qué se dice que 'el tiempo en el mercado' suele importar más que 'el momento perfecto para entrar' al invertir a largo plazo?",
        "opciones": [
            "Porque nunca hay que vender",
            "Porque el interés compuesto necesita tiempo para generar un efecto significativo",
            "Porque el mercado siempre sube todos los días",
            "Porque no importa cuándo invertís",
        ],
        "respuesta_correcta": 1,
        "explicacion": "El crecimiento compuesto se nota mucho más cuanto más tiempo esté invertido el dinero.",
        "dificultad": "dificil",
        "categoria": "inversion_riesgo",
    },
    {
        "texto": "Si el Banco Central sube fuerte la tasa de interés de referencia, ¿qué efecto es más probable sobre la inflación en el mediano plazo?",
        "opciones": [
            "La acelera",
            "Tiende a frenarla, al encarecer el crédito y desincentivar el consumo",
            "No tiene ningún efecto",
            "La elimina inmediatamente",
        ],
        "respuesta_correcta": 1,
        "explicacion": "Subir tasas suele encarecer los préstamos y desalentar el gasto, lo que tiende a moderar la inflación con el tiempo.",
        "dificultad": "dificil",
        "categoria": "otros",
    },
    {
        "texto": "¿Qué es el 'costo de oportunidad' de gastar $50.000 en algo hoy?",
        "opciones": [
            "El precio exacto que pagaste",
            "Lo que dejás de poder hacer con esa plata, como lo que hubiera generado si la invertías",
            "El IVA que pagaste",
            "No existe ese concepto",
        ],
        "respuesta_correcta": 1,
        "explicacion": "Cada decisión de gasto implica renunciar a otras alternativas posibles con ese mismo dinero.",
        "dificultad": "dificil",
        "categoria": "presupuesto",
    },
    {
        "texto": "¿Por qué diversificar entre activos poco relacionados entre sí reduce más el riesgo que diversificar entre activos muy parecidos?",
        "opciones": [
            "Porque así siempre ganás más",
            "Porque si uno cae, es menos probable que los otros caigan al mismo tiempo, suavizando la pérdida total",
            "No hay diferencia entre diversificar en activos parecidos o distintos",
            "Porque reduce los impuestos",
        ],
        "respuesta_correcta": 1,
        "explicacion": "La diversificación reduce más el riesgo cuando los activos no reaccionan todos igual ante los mismos eventos.",
        "dificultad": "dificil",
        "categoria": "inversion_riesgo",
    },
]
