"""Banco de preguntas de educación financiera para secundario.

Cada pregunta: texto, 4 opciones, índice de la correcta (0-3), explicación breve,
dificultad y categoría. Se cargan vía el management command `seed_preguntas`
(idempotente por `texto`: si cambiás las opciones/explicación de una pregunta
existente, correr el comando de nuevo la actualiza en vez de duplicarla — pero
si cambiás el `texto`, el comando la trata como una pregunta nueva).
"""

PREGUNTAS = [
    # --- FÁCIL ---
    {
        "texto": "¿Qué es un presupuesto personal?",
        "opciones": [
            "Un plan de cuánto esperás ganar y gastar en un período",
            "Un registro de todo lo que ya gastaste en el pasado",
            "El límite de dinero que un banco te deja pedir prestado",
            "Una cuenta de ahorro con interés fijo",
        ],
        "respuesta_correcta": 0,
        "explicacion": "Un presupuesto se arma ANTES para planificar; un registro de gastos pasados es otra herramienta distinta.",
        "dificultad": "facil",
        "categoria": "presupuesto",
    },
    {
        "texto": "Si ganás $10.000 por mes y gastás $12.000, ¿qué está pasando?",
        "opciones": [
            "Estás en déficit: gastás más de lo que ganás",
            "Tenés un superávit de $2.000",
            "Estás ahorrando $2.000 por mes",
            "Tu presupuesto está equilibrado",
        ],
        "respuesta_correcta": 0,
        "explicacion": "Gastar más de lo que entra es déficit, no superávit ni ahorro; esa diferencia se cubre con deuda o ahorros previos.",
        "dificultad": "facil",
        "categoria": "ahorro",
    },
    {
        "texto": "¿Qué es el interés en un préstamo?",
        "opciones": [
            "El costo adicional que pagás por usar plata que no es tuya",
            "La parte del préstamo que el banco te perdona",
            "Una comisión única que se cobra el día que te prestan la plata",
            "El monto exacto que te prestaron, sin cambios",
        ],
        "respuesta_correcta": 0,
        "explicacion": "El interés se paga además de devolver el capital, y se acumula con el tiempo, no es un pago único.",
        "dificultad": "facil",
        "categoria": "deuda_interes",
    },
    {
        "texto": "¿Para qué sirve principalmente un banco?",
        "opciones": [
            "Para recibir depósitos, otorgar préstamos y ofrecer medios de pago",
            "Para fijar el precio oficial de los productos en los comercios",
            "Para cobrar impuestos en nombre del Estado",
            "Para emitir el documento de identidad de las personas",
        ],
        "respuesta_correcta": 0,
        "explicacion": "Los bancos son intermediarios financieros: reciben depósitos, prestan y facilitan pagos; no fijan precios ni cobran impuestos.",
        "dificultad": "facil",
        "categoria": "otros",
    },
    {
        "texto": "¿Cuál de estas es una buena razón para ahorrar?",
        "opciones": [
            "Tener un fondo para cubrir un imprevisto sin endeudarte",
            "Para pagar menos impuestos ese año",
            "Porque el banco te obliga a mantener un mínimo en la cuenta",
            "Porque el dinero ahorrado siempre rinde más que cualquier inversión",
        ],
        "respuesta_correcta": 0,
        "explicacion": "El fondo de emergencia es un colchón de liquidez ante imprevistos, no una estrategia de rendimiento ni un requisito bancario.",
        "dificultad": "facil",
        "categoria": "ahorro",
    },
    {
        "texto": "Un gasto 'fijo' es aquel que...",
        "opciones": [
            "Se repite todos los meses por un monto similar, como el alquiler",
            "Solo se paga una vez en la vida, como comprar un auto",
            "Cambia mucho de un mes a otro, como salir a comer",
            "Se paga únicamente en efectivo",
        ],
        "respuesta_correcta": 0,
        "explicacion": "Los gastos fijos se repiten con un monto parecido mes a mes; los variables (como salidas) cambian según tus decisiones.",
        "dificultad": "facil",
        "categoria": "presupuesto",
    },
    {
        "texto": "Si pedís prestado y no pagás a tiempo, generalmente...",
        "opciones": [
            "Se te suman intereses o multas por mora",
            "La deuda se cancela automáticamente a los 90 días",
            "El banco extiende el plazo sin ningún costo adicional",
            "No pasa nada si la deuda es menor a $50.000",
        ],
        "respuesta_correcta": 0,
        "explicacion": "Pagar tarde casi siempre implica un costo extra (mora); las deudas no se cancelan solas ni hay un piso libre de consecuencias.",
        "dificultad": "facil",
        "categoria": "deuda_interes",
    },
    # --- MEDIA ---
    {
        "texto": "¿Qué diferencia al interés compuesto del interés simple?",
        "opciones": [
            "El compuesto también genera intereses sobre los intereses ya acumulados",
            "El simple se calcula sobre el capital más los intereses previos",
            "No hay ninguna diferencia real entre ambos",
            "El compuesto solo se usa en préstamos, nunca en inversiones",
        ],
        "respuesta_correcta": 0,
        "explicacion": "En el interés compuesto, cada período los intereses se suman al capital y también generan interés ('interés sobre interés').",
        "dificultad": "media",
        "categoria": "deuda_interes",
    },
    {
        "texto": "En general, ¿qué relación existe entre riesgo y retorno esperado de una inversión?",
        "opciones": [
            "A mayor riesgo, generalmente mayor retorno potencial (y mayor posibilidad de pérdida)",
            "A mayor riesgo, siempre menor retorno esperado",
            "El riesgo y el retorno no tienen ninguna relación",
            "Las inversiones más riesgosas garantizan ganancias más altas",
        ],
        "respuesta_correcta": 0,
        "explicacion": "Mayor riesgo potencial no GARANTIZA mayor ganancia; solo implica mayor variabilidad de resultados posibles, buenos y malos.",
        "dificultad": "media",
        "categoria": "inversion_riesgo",
    },
    {
        "texto": "¿Qué significa 'diversificar' una inversión?",
        "opciones": [
            "Repartir el dinero en distintos activos para reducir el riesgo total",
            "Invertir todo en el activo que más subió el último año",
            "Cambiar de inversión todas las semanas buscando la mejor",
            "Guardar todo el dinero en un solo banco, aunque en varias cuentas",
        ],
        "respuesta_correcta": 0,
        "explicacion": "Diversificar es repartir entre activos distintos; tener varias cuentas en el mismo banco no diversifica el riesgo real.",
        "dificultad": "media",
        "categoria": "inversion_riesgo",
    },
    {
        "texto": "¿Qué es la inflación?",
        "opciones": [
            "La suba generalizada y sostenida de los precios de una economía",
            "La suba del precio de un solo producto puntual, como la carne",
            "La devaluación oficial de la moneda frente al dólar",
            "Un aumento de sueldos dispuesto por el gobierno",
        ],
        "respuesta_correcta": 0,
        "explicacion": "La inflación es un fenómeno general de precios, distinto de que suba un producto puntual o de la devaluación (relacionada, pero no lo mismo).",
        "dificultad": "media",
        "categoria": "otros",
    },
    {
        "texto": "Si la inflación anual es del 100% y tus ahorros están guardados sin generar ningún rendimiento, ¿qué pasa con tu poder de compra?",
        "opciones": [
            "Se reduce a la mitad aproximadamente",
            "Se mantiene exactamente igual",
            "Aumenta, porque tenés más billetes en el bolsillo",
            "Se duplica junto con los precios",
        ],
        "respuesta_correcta": 0,
        "explicacion": "Si los precios se duplican y tu dinero no crece, con la misma plata comprás la mitad de cosas que antes.",
        "dificultad": "media",
        "categoria": "ahorro",
    },
    {
        "texto": "La regla 50/30/20 sugiere destinar tus ingresos aproximadamente a...",
        "opciones": [
            "50% gastos esenciales, 30% deseos, 20% ahorro o pago de deudas",
            "50% ahorro, 30% gastos esenciales, 20% deseos",
            "100% a gastos, dejando el ahorro para cuando sobre algo",
            "50% deudas, 50% gastos, sin destinar nada al ahorro",
        ],
        "respuesta_correcta": 0,
        "explicacion": "Es una guía orientativa de reparto del ingreso, no una regla exacta obligatoria.",
        "dificultad": "media",
        "categoria": "presupuesto",
    },
    {
        "texto": "¿Cuál de estas suele ser la deuda con la tasa de interés más alta para una persona común?",
        "opciones": [
            "El saldo de una tarjeta de crédito no pagado a tiempo",
            "Un préstamo personal en cuotas fijas mensuales",
            "Un adelanto de sueldo acordado con tu empleador",
            "Ninguna deuda tiene una tasa de interés más alta que otra",
        ],
        "respuesta_correcta": 0,
        "explicacion": "Las tarjetas de crédito suelen tener de las tasas más altas del mercado si no pagás el saldo total a tiempo.",
        "dificultad": "media",
        "categoria": "deuda_interes",
    },
    {
        "texto": "Depositás plata a un plazo fijo con una TNA del 40%, pero la inflación anual es del 60%. En términos reales, tu dinero...",
        "opciones": [
            "Pierde poder de compra, aunque en pesos haya crecido",
            "Gana poder de compra porque generó intereses",
            "Se mantiene exactamente igual en poder de compra",
            "Es imposible saberlo sin conocer el monto inicial",
        ],
        "respuesta_correcta": 0,
        "explicacion": "Si la tasa de interés (40%) es menor que la inflación (60%), tu dinero crece en pesos pero pierde poder de compra real.",
        "dificultad": "media",
        "categoria": "ahorro",
    },
    {
        "texto": "¿Qué es un 'gasto hormiga'?",
        "opciones": [
            "Pequeños gastos frecuentes que, sumados, impactan fuerte en el presupuesto",
            "Un gasto único y muy grande, como comprar una casa",
            "Un gasto que el banco te descuenta automáticamente sin avisar",
            "Un impuesto que se paga solo una vez al año",
        ],
        "respuesta_correcta": 0,
        "explicacion": "Los gastos hormiga son chicos e individualmente parecen insignificantes (un café, una app), pero sumados en el mes son un monto grande.",
        "dificultad": "media",
        "categoria": "presupuesto",
    },
    # --- DIFÍCIL ---
    {
        "texto": "¿Qué es la 'liquidez' de una inversión?",
        "opciones": [
            "Qué tan rápido podés convertirla en dinero disponible sin perder mucho valor",
            "El monto total de dinero que tenés invertido",
            "La ganancia porcentual que te dio esa inversión",
            "El riesgo de que una inversión pierda valor",
        ],
        "respuesta_correcta": 0,
        "explicacion": "Liquidez es sobre velocidad y facilidad de conversión a efectivo, no sobre el monto, la ganancia ni el riesgo directamente.",
        "dificultad": "dificil",
        "categoria": "inversion_riesgo",
    },
    {
        "texto": "Un préstamo tiene una TNA (Tasa Nominal Anual) del 60% pero una TEA (Tasa Efectiva Anual) del 79%. ¿Por qué son distintas?",
        "opciones": [
            "La TEA incluye el efecto de la capitalización de intereses durante el año, la TNA no",
            "Es un error de cálculo, ambas tasas deberían ser siempre iguales",
            "La TNA siempre es mayor que la TEA en cualquier préstamo",
            "La diferencia depende solo del banco, no tiene una razón matemática",
        ],
        "respuesta_correcta": 0,
        "explicacion": "La TEA refleja el costo real anual considerando cómo se capitalizan los intereses; por eso suele ser mayor que la TNA nominal.",
        "dificultad": "dificil",
        "categoria": "deuda_interes",
    },
    {
        "texto": "¿Por qué se dice que 'el tiempo en el mercado' suele importar más que 'el momento perfecto para entrar' al invertir a largo plazo?",
        "opciones": [
            "Porque el interés compuesto necesita tiempo para generar un efecto significativo",
            "Porque los mercados solo suben en el largo plazo, nunca bajan",
            "Porque el 'momento perfecto' no influye en nada del resultado final",
            "Porque cuanto más tiempo invertido, el riesgo de perder baja a cero",
        ],
        "respuesta_correcta": 0,
        "explicacion": "El crecimiento compuesto se nota mucho más con el tiempo; esto no significa que el riesgo desaparezca ni que el mercado nunca baje.",
        "dificultad": "dificil",
        "categoria": "inversion_riesgo",
    },
    {
        "texto": "Si el Banco Central sube fuerte la tasa de interés de referencia, ¿qué efecto es más probable sobre la inflación en el mediano plazo?",
        "opciones": [
            "Tiende a frenarla, al encarecer el crédito y desincentivar el consumo",
            "La acelera, porque suben los costos de las empresas",
            "No tiene ningún efecto sobre los precios",
            "Elimina la inflación de forma inmediata y permanente",
        ],
        "respuesta_correcta": 0,
        "explicacion": "Subir tasas encarece el crédito y desalienta el gasto, lo que tiende a moderar la inflación con el tiempo, no de forma inmediata ni garantizada.",
        "dificultad": "dificil",
        "categoria": "otros",
    },
    {
        "texto": "¿Qué es el 'costo de oportunidad' de gastar $50.000 en algo hoy?",
        "opciones": [
            "Lo que dejás de poder hacer con esa plata, como lo que hubiera generado si la invertías",
            "El precio exacto que pagaste, incluyendo impuestos",
            "La diferencia entre el precio de lista y el precio final con descuento",
            "El interés que te cobra el banco si pagás en cuotas",
        ],
        "respuesta_correcta": 0,
        "explicacion": "El costo de oportunidad es lo que renunciás al elegir una opción sobre otra, no el precio en sí ni un interés.",
        "dificultad": "dificil",
        "categoria": "presupuesto",
    },
    {
        "texto": "¿Por qué diversificar entre activos poco relacionados entre sí reduce más el riesgo que diversificar entre activos muy parecidos?",
        "opciones": [
            "Porque si uno cae, es menos probable que los otros caigan al mismo tiempo, suavizando la pérdida total",
            "Porque los activos parecidos siempre rinden menos que los distintos",
            "No hay diferencia real entre diversificar en activos parecidos o distintos",
            "Porque reduce automáticamente los impuestos que pagás",
        ],
        "respuesta_correcta": 0,
        "explicacion": "La diversificación reduce más el riesgo cuando los activos no reaccionan todos igual ante los mismos eventos (baja correlación entre ellos).",
        "dificultad": "dificil",
        "categoria": "inversion_riesgo",
    },
    {
        "texto": "Si un activo tiene una 'beta' mayor a 1 respecto al mercado, eso indica que...",
        "opciones": [
            "Tiende a moverse con más volatilidad que el mercado en general",
            "Siempre da mejores resultados que el mercado",
            "No tiene ninguna relación con los movimientos del mercado",
            "Es un activo libre de riesgo",
        ],
        "respuesta_correcta": 0,
        "explicacion": "La beta mide la sensibilidad de un activo respecto al mercado; mayor a 1 implica que se mueve, en promedio, con más amplitud (para bien y para mal).",
        "dificultad": "dificil",
        "categoria": "inversion_riesgo",
    },
    {
        "texto": "¿Por qué un aumento fuerte en la deuda pública de un país puede presionar al alza la tasa de interés que ese país paga para financiarse?",
        "opciones": [
            "Porque los prestamistas piden una tasa mayor para compensar el riesgo percibido de no cobrar",
            "Porque la ley obliga a subir la tasa cuando sube la deuda",
            "Porque más deuda pública reduce automáticamente la inflación",
            "No existe ninguna relación entre deuda pública y tasas de interés",
        ],
        "respuesta_correcta": 0,
        "explicacion": "A mayor deuda (y mayor riesgo percibido de no pago), los inversores exigen una tasa más alta para compensar ese riesgo adicional.",
        "dificultad": "dificil",
        "categoria": "deuda_interes",
    },
    {
        "texto": "Dos inversiones tienen el mismo retorno esperado, pero una es mucho más volátil que la otra. Según la relación riesgo-retorno, ¿cuál conviene elegir?",
        "opciones": [
            "La de menor volatilidad, porque da el mismo retorno esperado con menos riesgo",
            "La de mayor volatilidad, porque siempre termina compensando con más ganancia",
            "Da exactamente lo mismo, el retorno esperado es lo único que importa",
            "Ninguna: hay que elegir siempre la de mayor retorno esperado sin mirar el riesgo",
        ],
        "respuesta_correcta": 0,
        "explicacion": "Entre dos opciones con igual retorno esperado, la más eficiente es la de menor riesgo para lograr ese mismo resultado.",
        "dificultad": "dificil",
        "categoria": "inversion_riesgo",
    },
    {
        "texto": "¿Qué significa que un préstamo use un sistema de amortización 'francés'?",
        "opciones": [
            "Las cuotas son de monto fijo, pero la proporción de interés y capital dentro de cada una va cambiando",
            "Todas las cuotas tienen el mismo monto de capital y el mismo monto de interés",
            "El préstamo se paga íntegro en la última cuota, sin cuotas intermedias",
            "Es un sistema exclusivo de bancos franceses, no se usa en Argentina",
        ],
        "respuesta_correcta": 0,
        "explicacion": "En el sistema francés la cuota total es constante, pero al principio pagás más interés y menos capital, y esa proporción se invierte con el tiempo.",
        "dificultad": "dificil",
        "categoria": "deuda_interes",
    },
]
